// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"
#include "../ebook/ui_ebook_reader.h"
#include <string.h>
#include <stdio.h>
#include "tal_thread.h"  // TuyaOS thread API
#include "tal_memory.h"  // TuyaOS memory API
#include "tal_system.h"  // TuyaOS system API (tal_system_sleep)
#include "tal_log.h"     // TuyaOS log API (PR_DEBUG, PR_INFO, PR_ERR)
#include "lv_vendor.h"   // LVGL vendor API (lv_vendor_disp_lock/unlock)

#define TF_CARD_ROOT_PATH "/sdcard"

/* Debug macro - use TuyaOS log system */
#define EPUB_DEBUG(fmt, ...) PR_DEBUG("[EPUB] " fmt, ##__VA_ARGS__)

lv_obj_t * ui_file_screen = NULL;
lv_obj_t * ui_file_screen_file_container = NULL;
lv_obj_t * ui_file_screen_Image4 = NULL;

/* File screen state */
static struct {
    char *current_filepath;
    ui_fs_file_type_t file_type;
    ui_ebook_reader_t *ebook_reader;
    bool is_ebook_mode;
} file_screen_state = {0};

/* Loading state for async file loading */
typedef struct {
    lv_obj_t *loading_screen;    // Semi-transparent overlay
    lv_obj_t *loading_label;     // "Loading..." text
    lv_obj_t *loading_spinner;   // Optional spinner animation
    bool is_loading;             // Loading flag
} file_load_ui_state_t;

static file_load_ui_state_t load_ui_state = {0};

/* Background loading thread state */
static THREAD_HANDLE s_load_thread = NULL;
static volatile bool s_is_loading = false;
static volatile bool s_cancel_loading = false;

/* Forward declarations */
static void ui_file_screen_keyboard_handler(lv_event_t *e);
static void ui_file_screen_keyboard_enter(void);
static void ui_file_screen_keyboard_esc(void);
static void ui_file_screen_keyboard_prev_page(void);
static void ui_file_screen_keyboard_next_page(void);
static void ui_file_screen_click_handler(lv_event_t *e);
static void ui_file_screen_load_file(const char *filepath, ui_fs_file_type_t file_type);
static void ui_file_screen_keyboard_group_init(void);
static void ui_file_screen_keyboard_group_destroy(void);

/* Loading UI functions */
static void create_loading_ui(void);
static void show_loading_ui(bool show);
static void update_loading_status(const char *status);
static void cleanup_loading_ui(void);

/* Public function to get current filepath */
const char *ui_file_screen_get_current_filepath(void)
{
    return file_screen_state.current_filepath;
}

/* Keyboard group */
static lv_group_t *sg_keyboard_group = NULL;

/* ============================================================================
 * Loading UI Functions (for async file loading)
 * ============================================================================ */

/* Create loading overlay UI */
static void create_loading_ui(void)
{
    if (load_ui_state.loading_screen) {
        EPUB_DEBUG("Loading UI already exists");
        return; // Already created
    }
    
    EPUB_DEBUG("Creating loading UI overlay...");
    
    /* Create semi-transparent overlay */
    load_ui_state.loading_screen = lv_obj_create(lv_screen_active());
    if (!load_ui_state.loading_screen) {
        LV_LOG_ERROR("Failed to create loading screen");
        return;
    }
    
    lv_obj_set_size(load_ui_state.loading_screen, LV_PCT(100), LV_PCT(100));
    lv_obj_set_pos(load_ui_state.loading_screen, 0, 0);
    lv_obj_set_style_bg_color(load_ui_state.loading_screen, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(load_ui_state.loading_screen, LV_OPA_60, 0);
    lv_obj_set_style_border_width(load_ui_state.loading_screen, 0, 0);
    lv_obj_remove_flag(load_ui_state.loading_screen, LV_OBJ_FLAG_SCROLLABLE);
    
    /* Create loading label */
    load_ui_state.loading_label = lv_label_create(load_ui_state.loading_screen);
    if (load_ui_state.loading_label) {
        lv_label_set_text(load_ui_state.loading_label, "Loading EPUB...");
        lv_obj_set_style_text_color(load_ui_state.loading_label, lv_color_white(), 0);
        lv_obj_set_style_text_font(load_ui_state.loading_label, &lv_font_montserrat_14, 0);
        lv_obj_center(load_ui_state.loading_label);
    }
    
    /* Hide by default */
    lv_obj_add_flag(load_ui_state.loading_screen, LV_OBJ_FLAG_HIDDEN);
    
    EPUB_DEBUG("Loading UI created successfully, screen=%p, label=%p", 
               load_ui_state.loading_screen, load_ui_state.loading_label);
}

/* Show or hide loading UI */
static void show_loading_ui(bool show)
{
    EPUB_DEBUG("show_loading_ui(%d), screen=%p", show, load_ui_state.loading_screen);
    
    if (!load_ui_state.loading_screen) {
        EPUB_DEBUG("Creating loading UI...");
        create_loading_ui();
        EPUB_DEBUG("Loading UI created, screen=%p", load_ui_state.loading_screen);
    }
    
    if (!load_ui_state.loading_screen) {
        EPUB_DEBUG("ERROR: Loading screen not available!");
        return;
    }
    
    if (show) {
        lv_obj_remove_flag(load_ui_state.loading_screen, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(load_ui_state.loading_screen);
        load_ui_state.is_loading = true;
        EPUB_DEBUG("Loading UI shown");
    } else {
        lv_obj_add_flag(load_ui_state.loading_screen, LV_OBJ_FLAG_HIDDEN);
        load_ui_state.is_loading = false;
        EPUB_DEBUG("Loading UI hidden");
    }
}

/* Update loading status text */
static void update_loading_status(const char *status)
{
    if (load_ui_state.loading_label && status) {
        lv_label_set_text(load_ui_state.loading_label, status);
        LV_LOG_USER("Loading status: %s", status);
    }
}

/* Cleanup loading UI */
static void cleanup_loading_ui(void)
{
    if (load_ui_state.loading_screen) {
        lv_obj_del(load_ui_state.loading_screen);
        load_ui_state.loading_screen = NULL;
        load_ui_state.loading_label = NULL;
        load_ui_state.loading_spinner = NULL;
        load_ui_state.is_loading = false;
        LV_LOG_USER("Loading UI cleaned up");
    }
}

/* ============================================================================
 * Async File Loading with Background Thread
 * ============================================================================ */

/* Structure to pass data to loading thread */
typedef struct {
    char filepath[512];
    char full_path[512];
    ui_fs_file_type_t file_type;
    lv_obj_t *container;
} load_task_data_t;

/* Timer callback to hide error message and show error image */
static void error_timer_callback(lv_timer_t *timer)
{
    (void)timer;
    
    show_loading_ui(false);
    
    if (ui_file_screen_Image4) {
        lv_obj_remove_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
        lv_image_set_src(ui_file_screen_Image4, &ui_img_image_floder_wallpaper_png);
    }
}

/* Callback when file loading completes (called from background thread) */
static void on_file_loaded_callback(ui_ebook_reader_t *reader, ui_fs_file_type_t file_type)
{
    (void)file_type; // Unused parameter
    
    PR_DEBUG("[EPUB] ========================================");
    PR_DEBUG("[EPUB] Callback: ENTER - reader=%p", reader);
    PR_DEBUG("[EPUB] ========================================");
    
    /* 🔒 CRITICAL: Acquire LVGL lock before touching any LVGL objects */
    PR_DEBUG("[EPUB] Callback: Trying to acquire LVGL lock...");
    lv_vendor_disp_lock();
    PR_DEBUG("[EPUB] Callback: ✅ LVGL lock acquired");
    {
        PR_DEBUG("[EPUB] Callback: Hiding loading UI...");
        /* Hide loading UI */
        show_loading_ui(false);
        PR_DEBUG("[EPUB] Callback: Loading UI hidden");
        
        if (reader) {
            PR_DEBUG("[EPUB] Callback: ✅ Reader is valid, setting up UI...");
            
            /* Success: Set reader and show content */
            file_screen_state.ebook_reader = reader;
            PR_DEBUG("[EPUB] Callback: ebook_reader set to %p", file_screen_state.ebook_reader);
            
            /* Hide error image, show file content */
            if (ui_file_screen_Image4) {
                PR_DEBUG("[EPUB] Callback: Hiding error image");
                lv_obj_add_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
            }
            
            /* Make sure container is visible */
            if (ui_file_screen_file_container) {
                PR_DEBUG("[EPUB] Callback: Ensuring container is visible");
                lv_obj_remove_flag(ui_file_screen_file_container, LV_OBJ_FLAG_HIDDEN);
            }
            
            /* 🎯 KEY: Display the first page of the ebook */
            PR_DEBUG("[EPUB] Callback: Calling ui_ebook_reader_display_page...");
            ui_ebook_reader_display_page(reader);
            PR_DEBUG("[EPUB] Callback: ui_ebook_reader_display_page completed");
            
            /* Force display refresh for e-ink displays */
            if (reader->text_label) {
                PR_DEBUG("[EPUB] Callback: Invalidating text_label for refresh");
                lv_obj_invalidate(reader->text_label);
            }
            if (ui_file_screen_file_container) {
                PR_DEBUG("[EPUB] Callback: Invalidating container for refresh");
                lv_obj_invalidate(ui_file_screen_file_container);
            }
            
            /* Trigger immediate LVGL redraw */
            PR_DEBUG("[EPUB] Callback: Triggering display refresh");
            lv_refr_now(NULL);
            
            PR_DEBUG("[EPUB] Callback: ✅✅✅ File loaded and displayed successfully! ✅✅✅");
        } else {
            PR_DEBUG("[EPUB] Callback: ❌ Reader is NULL - showing error");
            
            /* Failure: Show error */
            PR_DEBUG("[EPUB] Callback: Updating loading status to 'Load failed!'");
            
            /* Show error message briefly, then show error image */
            update_loading_status("Load failed!");
            show_loading_ui(true);
            
            PR_DEBUG("[EPUB] Callback: Creating error timer (2s)");
            /* Create a timer to hide error after 2 seconds */
            lv_timer_t *error_timer = lv_timer_create(error_timer_callback, 2000, NULL);
            if (error_timer) {
                lv_timer_set_repeat_count(error_timer, 1); // Run once
                PR_DEBUG("[EPUB] Callback: Error timer created");
            } else {
                PR_DEBUG("[EPUB] Callback: ❌ Failed to create error timer!");
            }
        }
    }
    PR_DEBUG("[EPUB] Callback: Releasing LVGL lock...");
    lv_vendor_disp_unlock();
    PR_DEBUG("[EPUB] Callback: ✅ LVGL lock released");
    PR_DEBUG("[EPUB] ========================================");
    PR_DEBUG("[EPUB] Callback: EXIT");
    PR_DEBUG("[EPUB] ========================================");
    /* 🔓 LVGL lock released */
}

/* Background thread function for loading files */
static void file_load_thread_func(void *arg)
{
    EPUB_DEBUG("=== Thread started, arg=%p ===", arg);
    
    load_task_data_t *task = (load_task_data_t *)arg;
    
    if (!task) {
        EPUB_DEBUG("ERROR: Invalid task data");
        s_is_loading = false;
        return;
    }
    
    EPUB_DEBUG("Task data valid, filepath=%s, type=%d", task->full_path, task->file_type);
    EPUB_DEBUG("Container=%p, cancel_flag=%d", task->container, s_cancel_loading);
    
    ui_ebook_reader_t *reader = NULL;
    
    /* Check if loading was cancelled */
    if (s_cancel_loading) {
        EPUB_DEBUG("Loading cancelled before start");
        goto cleanup;
    }
    
    EPUB_DEBUG("Starting ui_ebook_reader_init...");
    
    /* ⚠️ TIME-CONSUMING OPERATION (1-5 seconds for EPUB extraction)
     * No LVGL lock needed here - we're in a background thread
     */
    if (task->file_type == UI_FS_FILE_TYPE_FILE_EPUB || 
        task->file_type == UI_FS_FILE_TYPE_FILE_TEXT) {
        
        /* Check cancellation before starting */
        if (s_cancel_loading) {
            EPUB_DEBUG("Loading cancelled");
            goto cleanup;
        }
        
        EPUB_DEBUG("Calling ui_ebook_reader_init with path: %s", task->full_path);
        
        /* Initialize ebook reader (this extracts ZIP, parses XML, etc.) */
        reader = ui_ebook_reader_init(task->full_path, task->container);
        
        EPUB_DEBUG("ui_ebook_reader_init returned: %p", reader);
        
        if (reader) {
            EPUB_DEBUG("✅ Reader initialized successfully!");
        } else {
            EPUB_DEBUG("❌ Reader initialization failed (returned NULL)");
        }
    }
    
cleanup:
    EPUB_DEBUG("Entering cleanup, reader=%p", reader);
    EPUB_DEBUG("About to call callback...");
    
    /* Notify completion via callback */
    on_file_loaded_callback(reader, task->file_type);
    
    EPUB_DEBUG("After callback - callback executed successfully");
    
    /* Cleanup */
    tal_free(task);
    s_is_loading = false;
    s_load_thread = NULL;
    
    EPUB_DEBUG("=== Thread exiting ===");
}

/* ============================================================================
 * File Operations
 * ============================================================================ */

/* Public function to open a file */
void ui_file_screen_open_file(const char *filepath, ui_fs_file_type_t file_type)
{
    if (!filepath) {
        return;
    }

    /* Switch to file screen */
    _ui_screen_change(&ui_file_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_file_screen_screen_init);

    /* Load the file */
    ui_file_screen_load_file(filepath, file_type);
}

/* Load file into screen */
static void ui_file_screen_load_file(const char *filepath, ui_fs_file_type_t file_type)
{
    /* Cleanup previous state */
    if (file_screen_state.ebook_reader) {
        ui_ebook_reader_cleanup(file_screen_state.ebook_reader);
        file_screen_state.ebook_reader = NULL;
    }

    if (file_screen_state.current_filepath) {
        lv_free(file_screen_state.current_filepath);
        file_screen_state.current_filepath = NULL;
    }

    /* Store file info */
    file_screen_state.current_filepath = lv_malloc(strlen(filepath) + 1);
    if (file_screen_state.current_filepath) {
        strcpy(file_screen_state.current_filepath, filepath);
    }
    file_screen_state.file_type = file_type;
    file_screen_state.is_ebook_mode = false;

    /* Build full path */
    char full_path[512];
    if (filepath[0] == '/') {
        /* Absolute path */
        strncpy(full_path, filepath, sizeof(full_path) - 1);
        full_path[sizeof(full_path) - 1] = '\0';
    } else {
        /* Relative to FS_PATH */
        snprintf(full_path, sizeof(full_path), "%s/%s", TF_CARD_ROOT_PATH, filepath);
    }

    /* Hide image by default */
    if (ui_file_screen_Image4) {
        lv_obj_add_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
    }

    /* Check file type and load accordingly */
    if (file_type == UI_FS_FILE_TYPE_FILE_EPUB || file_type == UI_FS_FILE_TYPE_FILE_TEXT) {
        /* ============================================
         * ASYNC EBOOK LOADING (方案3：最优方案)
         * ============================================ */
        
        file_screen_state.is_ebook_mode = true;
        
        /* Check if already loading */
        if (s_is_loading) {
            LV_LOG_WARN("Already loading a file, please wait");
            update_loading_status("Already loading...");
            return;
        }
        
        /* Cancel any previous loading */
        s_cancel_loading = false;
        
        /* Show loading UI */
        show_loading_ui(true);
        update_loading_status("Loading EPUB...");
        
        /* Prepare task data for background thread */
        load_task_data_t *task = tal_malloc(sizeof(load_task_data_t));
        if (!task) {
            LV_LOG_ERROR("Failed to allocate task data");
            show_loading_ui(false);
            if (ui_file_screen_Image4) {
                lv_obj_remove_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
                lv_image_set_src(ui_file_screen_Image4, &ui_img_image_floder_wallpaper_png);
            }
            return;
        }
        
        /* Copy file paths to task */
        strncpy(task->filepath, filepath, sizeof(task->filepath) - 1);
        task->filepath[sizeof(task->filepath) - 1] = '\0';
        
        strncpy(task->full_path, full_path, sizeof(task->full_path) - 1);
        task->full_path[sizeof(task->full_path) - 1] = '\0';
        
        task->file_type = file_type;
        task->container = ui_file_screen_file_container;
        
        /* Create and start background loading thread */
        s_is_loading = true;
        
        THREAD_CFG_T thread_cfg = {
            .priority = THREAD_PRIO_2,      // Lower priority than UI
            .stackDepth = 16384,            // 16KB stack for EPUB extraction
            .thrdname = "epub_load",
            .psram_mode = 1
        };
        
        OPERATE_RET ret = tal_thread_create_and_start(
            &s_load_thread,
            NULL,
            NULL,
            file_load_thread_func,
            task,
            &thread_cfg
        );
        
        if (ret != OPRT_OK) {
            LV_LOG_ERROR("Failed to create loading thread: %d", ret);
            tal_free(task);
            s_is_loading = false;
            show_loading_ui(false);
            
            /* Fallback: Show error image */
            if (ui_file_screen_Image4) {
                lv_obj_remove_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
                lv_image_set_src(ui_file_screen_Image4, &ui_img_image_floder_wallpaper_png);
            }
        } else {
            EPUB_DEBUG("Loading thread created successfully, handle=%p", s_load_thread);
        }
        
    } else if (file_type == UI_FS_FILE_TYPE_FILE_PNG) {
        /* Image mode - load image */
        file_screen_state.is_ebook_mode = false;
        if (ui_file_screen_Image4) {
            lv_obj_clear_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
            /* Try to load image from file path */
            lv_image_set_src(ui_file_screen_Image4, full_path);
        }
    } else {
        /* Unknown type, show default image */
        if (ui_file_screen_Image4) {
            lv_obj_clear_flag(ui_file_screen_Image4, LV_OBJ_FLAG_HIDDEN);
            lv_image_set_src(ui_file_screen_Image4, &ui_img_image_floder_wallpaper_png);
        }
    }
}

/* Keyboard handler - handles ENTER */
static void ui_file_screen_keyboard_enter(void)
{
    /* ENTER key handling removed - menu functionality removed */
}

/* Keyboard handler - handles ESC to exit */
static void ui_file_screen_keyboard_esc(void)
{
    /* If loading, cancel it */
    if (s_is_loading) {
        LV_LOG_USER("ESC pressed: cancelling file loading");
        s_cancel_loading = true;
        update_loading_status("Cancelling...");
        
        /* Wait briefly for cancellation */
        int wait_count = 0;
        while (s_is_loading && wait_count < 5) {
            tal_system_sleep(100);
            wait_count++;
        }
        
        show_loading_ui(false);
    }
    
    /* Exit file screen and return to folder screen */
    _ui_screen_change(&ui_floder_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_floder_screen_screen_init);
    LV_LOG_USER("ui_file_screen_keyboard_esc: exited file screen");
}

/* Keyboard handler - handles LEFT to go to previous page */
static void ui_file_screen_keyboard_prev_page(void)
{
    if (file_screen_state.is_ebook_mode && file_screen_state.ebook_reader) {
        ui_ebook_reader_prev_page(file_screen_state.ebook_reader);
        LV_LOG_USER("ui_file_screen_keyboard_prev_page: previous page");
    }
}

/* Keyboard handler - handles RIGHT to go to next page */
static void ui_file_screen_keyboard_next_page(void)
{
    if (file_screen_state.is_ebook_mode && file_screen_state.ebook_reader) {
        ui_ebook_reader_next_page(file_screen_state.ebook_reader);
        LV_LOG_USER("ui_file_screen_keyboard_next_page: next page");
    }
}

/* Click handler - intercept clicks in ebook mode */
static void ui_file_screen_click_handler(lv_event_t *e)
{
    /* Click handling - menu functionality removed */
    (void)e;
}

/* Keyboard handler - main handler that routes key events */
static void ui_file_screen_keyboard_handler(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code != LV_EVENT_KEY) {
        return;
    }

    lv_key_t key = lv_event_get_key(e);

    /* Route keys to ebook reader if in ebook mode */
    if (file_screen_state.is_ebook_mode && file_screen_state.ebook_reader) {
        ui_ebook_reader_handle_key(file_screen_state.ebook_reader, key);
        return;
    }

    /* Handle non-ebook navigation */
    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
            ui_file_screen_keyboard_prev_page();
            LV_LOG_USER("ui_file_screen_keyboard_handler: UP or LEFT");
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
            ui_file_screen_keyboard_next_page();
            LV_LOG_USER("ui_file_screen_keyboard_handler: DOWN or RIGHT");
            break;
        case LV_KEY_ENTER:
            ui_file_screen_keyboard_enter();
            LV_LOG_USER("ui_file_screen_keyboard_handler: ENTER");
            break;
        case LV_KEY_ESC:
            ui_file_screen_keyboard_esc();
            LV_LOG_USER("ui_file_screen_keyboard_handler: ESC");
            break;
        default:
            break;
    }
}

// event functions
void ui_event_file_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_file_screen_loaded(e);
        // Initialize keyboard group
        ui_file_screen_keyboard_group_init();
    } else if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        // Cleanup keyboard group
        ui_file_screen_keyboard_group_destroy();
    }
}

// build functions

void ui_file_screen_screen_init(void)
{
    ui_file_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_file_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_file_screen, LV_OBJ_FLAG_CLICKABLE);          /// Make screen focusable for keyboard
    /* Prevent default ENTER behavior on screen - we handle it in keyboard handler */
    lv_obj_clear_flag(ui_file_screen, LV_OBJ_FLAG_SCROLLABLE);

    ui_file_screen_file_container = lv_obj_create(ui_file_screen);
    lv_obj_remove_style_all(ui_file_screen_file_container);
    lv_obj_set_width(ui_file_screen_file_container, lv_pct(100));
    lv_obj_set_height(ui_file_screen_file_container, lv_pct(100));
    lv_obj_set_align(ui_file_screen_file_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_file_screen_file_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    /* Prevent container from processing keyboard events - screen handles them */
    lv_obj_clear_flag(ui_file_screen_file_container, LV_OBJ_FLAG_CLICKABLE);

    ui_file_screen_Image4 = lv_image_create(ui_file_screen);
    lv_image_set_src(ui_file_screen_Image4, &ui_img_image_floder_wallpaper_png);
    lv_obj_set_width(ui_file_screen_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_file_screen_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_file_screen_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_file_screen_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_file_screen_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_file_screen, ui_event_file_screen, LV_EVENT_ALL, NULL);
    /* Add keyboard handler - handle ENTER before any default behavior */
    lv_obj_add_event_cb(ui_file_screen, ui_file_screen_keyboard_handler, LV_EVENT_KEY, NULL);
    /* Add click handler to intercept ENTER-triggered clicks in ebook mode */
    lv_obj_add_event_cb(ui_file_screen, ui_file_screen_click_handler, LV_EVENT_CLICKED, NULL);
}

/* Keyboard group initialization */
static void ui_file_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        lv_group_remove_all_objs(sg_keyboard_group);
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_file_screen_keyboard_group_init: failed to create group");
        return;
    }

    lv_group_add_obj(sg_keyboard_group, ui_file_screen);
    /* Set the screen as the focused object */
    lv_group_focus_obj(ui_file_screen);
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

/* Keyboard group cleanup */
static void ui_file_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

void ui_file_screen_screen_destroy(void)
{
    LV_LOG_USER("ui_file_screen_screen_destroy: cleaning up");
    
    /* Cancel any ongoing loading */
    if (s_is_loading) {
        LV_LOG_WARN("Cancelling ongoing file loading");
        s_cancel_loading = true;
        
        /* Wait briefly for thread to finish (don't block too long) */
        int wait_count = 0;
        while (s_is_loading && wait_count < 10) {
            tal_system_sleep(100); // Sleep 100ms
            wait_count++;
        }
        
        if (s_is_loading) {
            LV_LOG_ERROR("Loading thread did not finish in time");
        }
    }
    
    /* Cleanup loading UI */
    cleanup_loading_ui();
    
    /* Cleanup ebook reader */
    if (file_screen_state.ebook_reader) {
        ui_ebook_reader_cleanup(file_screen_state.ebook_reader);
        file_screen_state.ebook_reader = NULL;
    }

    if (file_screen_state.current_filepath) {
        lv_free(file_screen_state.current_filepath);
        file_screen_state.current_filepath = NULL;
    }

    if(ui_file_screen) lv_obj_del(ui_file_screen);

    // NULL screen variables
    ui_file_screen = NULL;
    ui_file_screen_file_container = NULL;
    ui_file_screen_Image4 = NULL;
    
    LV_LOG_USER("ui_file_screen_screen_destroy: complete");
}
