// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include <stdio.h>
#include "../ui.h"

lv_obj_t * ui_floder_screen = NULL;
lv_obj_t * ui_floder_screen_status_bar = NULL;
lv_obj_t * ui_floder_screen_battery = NULL;
lv_obj_t * ui_floder_screen_tf_card = NULL;
lv_obj_t * ui_floder_screen_remain_size = NULL;
lv_obj_t * ui_floder_screen_title = NULL;
lv_obj_t * ui_floder_screen_list_container = NULL;
/**************** extern keyboard group functions start ************************/
static void ui_floder_screen_keyboard_group_init(void);
static void ui_floder_screen_keyboard_group_destroy(void);

static void ui_floder_screen_keyboard_handler(lv_event_t * e);
/**************** extern keyboard group functions end ************************/
/****************************** file list start ******************************/
#define TF_CARD_ROOT_PATH "/sdcard"

static void ui_floder_screen_file_list_show(const char *path);
static void ui_floder_screen_file_list_render_page(uint32_t page);
static void ui_floder_screen_keyboard_focus_show(uint32_t index);
static uint32_t ui_floder_screen_calculate_items_per_page(void);

static ui_fs_file_list_t *sg_file_list = NULL;

#define UI_FLODER_PATH_MALLOC_ALIGN_SIZE 64
static char *sg_current_path = NULL;
static size_t sg_current_path_size = 0;  // 记录 sg_current_path 的实际分配大小

/****************************** keyboard focus start ******************************/
static uint32_t __focus_obj_count = 0;
static int32_t __focus_obj_current_index = 0;
static lv_group_t * sg_keyboard_group = NULL;

#define __FOCUS_OBJ_STACK_MAX_COUNT 64
static uint32_t __focus_obj_stack_index = 0;
static uint32_t __focus_obj_stack[__FOCUS_OBJ_STACK_MAX_COUNT] = {0};

/****************************** pagination start ******************************/
// Pagination settings for e-paper display (dynamically calculated)
static uint32_t __items_per_page = 0;   // Number of items per page (calculated dynamically)
static uint32_t __current_page = 0;     // Current page index (0-based)
static uint32_t __total_pages = 0;      // Total number of pages

/****************************** pagination end ******************************/

/****************************** keyboard focus end ******************************/

/****************************** file list end ******************************/
// event funtions
void ui_event_floder_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_floder_screen_loaded(e);

        // add keyboard group
        ui_floder_screen_keyboard_group_init();

        // init current path
        size_t path_len = strlen(TF_CARD_ROOT_PATH);
        sg_current_path_size = (path_len / UI_FLODER_PATH_MALLOC_ALIGN_SIZE + 1) * UI_FLODER_PATH_MALLOC_ALIGN_SIZE;
        sg_current_path = lv_malloc(sg_current_path_size);
        if (NULL != sg_current_path) {
            memset(sg_current_path, 0, sg_current_path_size);
            strncpy(sg_current_path, TF_CARD_ROOT_PATH, sg_current_path_size - 1);
        }

        // show file list
        ui_floder_screen_file_list_show(sg_current_path);
        // show focus object (only if folder is not empty)
        if (__focus_obj_count > 0) {
            ui_floder_screen_keyboard_focus_show(0);
        }
    } else if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        // cleanup resources
        ui_floder_screen_keyboard_group_destroy();

        // free file list
        if (NULL != sg_file_list) {
            ui_fs_file_list_destroy(sg_file_list);
            sg_file_list = NULL;
        }

        // free current path
        if (NULL != sg_current_path) {
            lv_free(sg_current_path);
            sg_current_path = NULL;
            sg_current_path_size = 0;
        }

        // reset focus index
        __focus_obj_count = 0;
        __focus_obj_current_index = 0;

        // reset pagination
        __items_per_page = 0;
        __current_page = 0;
        __total_pages = 0;
    } else if(event_code == LV_EVENT_KEY) {
        ui_floder_screen_keyboard_handler(e);
    } else if(event_code == LV_EVENT_APP_BATTERY) {
        ui_battery_event_handler(ui_floder_screen_battery);
    }
}

// build funtions

void ui_floder_screen_screen_init(void)
{
    ui_floder_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_floder_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_status_bar = lv_obj_create(ui_floder_screen);
    lv_obj_remove_style_all(ui_floder_screen_status_bar);
    lv_obj_set_height(ui_floder_screen_status_bar, 30);
    lv_obj_set_width(ui_floder_screen_status_bar, lv_pct(100));
    lv_obj_set_x(ui_floder_screen_status_bar, -1);
    lv_obj_set_y(ui_floder_screen_status_bar, 0);
    lv_obj_set_align(ui_floder_screen_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_floder_screen_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_floder_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_floder_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_foreground);
    lv_obj_set_style_border_width(ui_floder_screen_status_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_floder_screen_status_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floder_screen_battery = lv_image_create(ui_floder_screen_status_bar);
    lv_image_set_src(ui_floder_screen_battery, &ui_img_image_statue_bar_battery_battery_full_30_png);
    lv_obj_set_width(ui_floder_screen_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floder_screen_battery, -10);
    lv_obj_set_y(ui_floder_screen_battery, 0);
    lv_obj_set_align(ui_floder_screen_battery, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_floder_screen_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_floder_screen_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_tf_card = lv_image_create(ui_floder_screen_status_bar);
    lv_image_set_src(ui_floder_screen_tf_card, &ui_img_image_statue_bar_sd_tf_30_png);
    lv_obj_set_width(ui_floder_screen_tf_card, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_tf_card, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floder_screen_tf_card, 5);
    lv_obj_set_y(ui_floder_screen_tf_card, 0);
    lv_obj_set_align(ui_floder_screen_tf_card, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_floder_screen_tf_card, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_floder_screen_tf_card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_remain_size = lv_label_create(ui_floder_screen_status_bar);
    lv_obj_set_width(ui_floder_screen_remain_size, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_remain_size, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floder_screen_remain_size, 45);
    lv_obj_set_y(ui_floder_screen_remain_size, 0);
    lv_obj_set_align(ui_floder_screen_remain_size, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_floder_screen_remain_size, "31.25 GB(TF)");
    lv_obj_set_style_text_font(ui_floder_screen_remain_size, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floder_screen_title = lv_label_create(ui_floder_screen_status_bar);
    lv_obj_set_width(ui_floder_screen_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_floder_screen_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_floder_screen_title, "Floder");
    lv_obj_set_style_text_font(ui_floder_screen_title, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floder_screen_list_container = lv_obj_create(ui_floder_screen);
    lv_obj_remove_style_all(ui_floder_screen_list_container);
    lv_obj_set_height(ui_floder_screen_list_container, 270);
    lv_obj_set_width(ui_floder_screen_list_container, lv_pct(100));
    lv_obj_set_align(ui_floder_screen_list_container, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_floder_screen_list_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_floder_screen_list_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_floder_screen_list_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_floder_screen, ui_event_floder_screen, LV_EVENT_ALL, NULL);

}

void ui_floder_screen_screen_destroy(void)
{
    if(ui_floder_screen) lv_obj_del(ui_floder_screen);

    // NULL screen variables
    ui_floder_screen = NULL;
    ui_floder_screen_status_bar = NULL;
    ui_floder_screen_battery = NULL;
    ui_floder_screen_tf_card = NULL;
    ui_floder_screen_remain_size = NULL;
    ui_floder_screen_title = NULL;
    ui_floder_screen_list_container = NULL;

}

/****************************** keyboard start ******************************/

static void ui_floder_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        // add group to indev
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_floder_screen_keyboard_group_init: failed to create group");
        return;
    }

    // add ui_floder_screen to group
    lv_group_add_obj(sg_keyboard_group, ui_floder_screen);

    // add group to indev
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

static void ui_floder_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

/**
 * @brief Show focus on a specific item (index relative to current page)
 *
 * @param index Item index on current page (0 to items_per_page-1)
 */
static void ui_floder_screen_keyboard_focus_show(uint32_t index)
{
    lv_obj_t *last_focus_obj = NULL;
    lv_obj_t *focus_obj = NULL;
    ui_fs_file_node_t *node = NULL;

    // Calculate items on current page
    uint32_t start_index = __current_page * __items_per_page;
    uint32_t end_index = start_index + __items_per_page;
    if (end_index > __focus_obj_count) {
        end_index = __focus_obj_count;
    }
    uint32_t items_on_current_page = end_index - start_index;

    // Validate index
    if (index >= items_on_current_page) {
        return;
    }

    // Get last focus object (using current page-relative index)
    uint32_t last_global_index = start_index + __focus_obj_current_index;
    if (last_global_index < __focus_obj_count) {
        node = ui_fs_file_list_get_node_by_index(sg_file_list, last_global_index);
        if (node != NULL) {
            last_focus_obj = (lv_obj_t *)node->user_data;
        }
    }

    // Get new focus object (convert page-relative index to global index)
    uint32_t global_index = start_index + index;
    node = ui_fs_file_list_get_node_by_index(sg_file_list, global_index);
    if (node == NULL) {
        return;
    }

    focus_obj = (lv_obj_t *)node->user_data;
    if (NULL == focus_obj) {
        return;
    }

    // Defocus last focus object
    if (NULL != last_focus_obj) {
        lv_obj_send_event(last_focus_obj, LV_EVENT_DEFOCUSED, NULL);
        // LV_LOG_USER("defocus last focus object: %p (global index: %d)", last_focus_obj, last_global_index);
    }

    // Focus new focus object (store page-relative index)
    __focus_obj_current_index = index;
    lv_obj_send_event(focus_obj, LV_EVENT_FOCUSED, NULL);
    // LV_LOG_USER("focus new focus object: %p (page: %d, page index: %d, global index: %d)",
    //             focus_obj, __current_page, index, global_index);
}

/**
 * @brief Move focus to previous item with pagination support
 *
 * For e-paper display, when moving to previous page, refresh the display
 * to show the new page content. Stops at the first item (no wrap around).
 */
static void ui_floder_screen_keyboard_focus_prev(void)
{
    // Check if folder is empty
    if (__focus_obj_count == 0) {
        LV_LOG_USER("Empty folder, cannot move focus");
        return;
    }

    int32_t index = __focus_obj_current_index - 1;

    // Check if we need to go to previous page
    if (index < 0) {
        if (__current_page == 0) {
            // At first page and first item, do nothing (stop here)
            LV_LOG_USER("Already at first item, cannot go previous");
            return;
        } else {
            // Go to previous page, focus on last item
            __current_page--;
            ui_floder_screen_file_list_render_page(__current_page);

            // Calculate items on the new current page
            uint32_t start_index = __current_page * __items_per_page;
            uint32_t end_index = start_index + __items_per_page;
            if (end_index > __focus_obj_count) {
                end_index = __focus_obj_count;
            }
            uint32_t items_on_page = end_index - start_index;

            // Focus on last item of previous page
            index = items_on_page - 1;
        }
    }

    ui_floder_screen_keyboard_focus_show(index);
}

/**
 * @brief Move focus to next item with pagination support
 *
 * For e-paper display, when moving to next page, refresh the display
 * to show the new page content. Stops at the last item (no wrap around).
 */
static void ui_floder_screen_keyboard_focus_next(void)
{
    // Check if folder is empty
    if (__focus_obj_count == 0) {
        LV_LOG_USER("Empty folder, cannot move focus");
        return;
    }

    // Calculate items on current page
    uint32_t start_index = __current_page * __items_per_page;
    uint32_t end_index = start_index + __items_per_page;
    if (end_index > __focus_obj_count) {
        end_index = __focus_obj_count;
    }
    int32_t items_on_current_page = (int32_t)(end_index - start_index);

    int32_t index = __focus_obj_current_index + 1;

    // Check if we need to go to next page
    if (index >= items_on_current_page) {
        // Move to next page
        if (__current_page < __total_pages - 1) {
            // Go to next page
            __current_page++;
            ui_floder_screen_file_list_render_page(__current_page);
            index = 0;
        } else {
            // At last page and last item, do nothing (stop here)
            LV_LOG_USER("Already at last item, cannot go next");
            return;
        }
    }

    ui_floder_screen_keyboard_focus_show(index);
}

static void ui_floder_screen_keyboard_enter(void)
{
    // Check if folder is empty
    if (__focus_obj_count == 0) {
        LV_LOG_USER("Empty folder, cannot enter");
        return;
    }

    // Calculate global index from current page and page-relative index
    uint32_t global_index = __current_page * __items_per_page + __focus_obj_current_index;

    if (global_index >= __focus_obj_count) {
        return;
    }

    // get focus object
    ui_fs_file_node_t *node = ui_fs_file_list_get_node_by_index(sg_file_list, global_index);
    if (NULL == node) {
        return;
    }
    lv_obj_t *focus_obj = (lv_obj_t *)node->user_data;
    if (NULL == focus_obj) {
        return;
    }

    // Only enter directories, not files
    if (node->type != UI_FS_FILE_TYPE_DIRECTORY) {
        /* Open file in file screen */
        char full_path[512];
        size_t path_len = strlen(sg_current_path);

        int need_slash = 0;
        if (path_len > 0 && sg_current_path[path_len - 1] != '/') {
            need_slash = 1;
        }

        snprintf(full_path, sizeof(full_path), "%s%s%s", sg_current_path,
                 need_slash ? "/" : "", node->name);

        /* Remove TF_CARD_ROOT_PATH prefix if present */
        const char *relative_path = full_path;
        if (strncmp(full_path, TF_CARD_ROOT_PATH, strlen(TF_CARD_ROOT_PATH)) == 0) {
            relative_path = full_path + strlen(TF_CARD_ROOT_PATH);
            if (*relative_path == '/') {
                relative_path++;
            }
        }

        ui_file_screen_open_file(relative_path, node->type);
        LV_LOG_USER("Opening file: %s (type: %d)", relative_path, node->type);
        return;
    }

    // get path
    size_t path_len = strlen(sg_current_path);
    size_t name_len = strlen(node->name);

    // 检查路径末尾是否带有'/'
    int need_slash = 0;
    if (path_len > 0 && sg_current_path[path_len - 1] != '/') {
        need_slash = 1;
    }

    // 计算新路径所需的总长度（包括 '\0'）
    size_t total_len = path_len + need_slash + name_len + 1;

    // 比较所需长度与当前分配的大小
    if (total_len > sg_current_path_size) {
        // 需要重新分配更大的内存
        size_t new_size = ((total_len - 1) / UI_FLODER_PATH_MALLOC_ALIGN_SIZE + 1) * UI_FLODER_PATH_MALLOC_ALIGN_SIZE;
        char *new_path = lv_malloc(new_size);
        if (NULL == new_path) {
            LV_LOG_ERROR("ui_floder_screen_keyboard_enter: failed to allocate memory");
            return;
        }
        memset(new_path, 0, new_size);

        // 拷贝原路径
        strncpy(new_path, sg_current_path, new_size - 1);

        // 释放旧内存
        lv_free(sg_current_path);
        sg_current_path = new_path;
        sg_current_path_size = new_size;

        // 更新 path_len（虽然应该不变，但为了安全）
        path_len = strlen(sg_current_path);
    }

    size_t offset = path_len;
    if (need_slash) {
        if (offset + 1 < sg_current_path_size) {
            sg_current_path[offset] = '/';
            offset += 1;
        }
    }

    // 拷贝文件名，确保不超过剩余空间
    size_t remaining = sg_current_path_size - offset;
    if (remaining > 0) {
        strncpy(sg_current_path + offset, node->name, remaining - 1);
        sg_current_path[sg_current_path_size - 1] = '\0';  // 确保字符串终止
    }

    // push focus object global index to stack
    if (__focus_obj_stack_index < __FOCUS_OBJ_STACK_MAX_COUNT) {
        __focus_obj_stack[__focus_obj_stack_index] = global_index;
    }
    __focus_obj_stack_index++;

    // show file list (this will reset to page 0)
    ui_floder_screen_file_list_show(sg_current_path);

    // show focus object (start at first item of first page, only if not empty)
    if (__focus_obj_count > 0) {
        ui_floder_screen_keyboard_focus_show(0);
    }

    return;
}

static void ui_floder_screen_keyboard_esc(void)
{
    if (NULL == sg_current_path) {
        return;
    }

    // 如果当前路径是根目录，则返回主界面
    if (__focus_obj_stack_index == 0) {
        _ui_screen_change(&ui_home_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_home_screen_screen_init);
        return;
    }

    // 返回上一级界面， 分隔符 '/'
    size_t path_len = strlen(sg_current_path);
    for (size_t i = path_len - 1; i > 0; i--) {
        if (sg_current_path[i] == '/') {
            sg_current_path[i] = '\0';
            break;
        }
    }

    // pop focus object global index from stack
    uint32_t saved_global_index = 0;
    if (__focus_obj_stack_index > 0) {
        __focus_obj_stack_index--;
    }

    if (__focus_obj_stack_index < __FOCUS_OBJ_STACK_MAX_COUNT) {
        saved_global_index = __focus_obj_stack[__focus_obj_stack_index];
    }

    // show file list (this will reset to page 0)
    ui_floder_screen_file_list_show(sg_current_path);

    // Calculate which page the saved item is on
    __current_page = saved_global_index / __items_per_page;
    if (__current_page >= __total_pages) {
        __current_page = __total_pages > 0 ? __total_pages - 1 : 0;
    }

    // Render the page containing the previously focused item
    ui_floder_screen_file_list_render_page(__current_page);

    // Calculate page-relative index
    uint32_t page_relative_index = saved_global_index - (__current_page * __items_per_page);

    // Validate page-relative index
    uint32_t start_index = __current_page * __items_per_page;
    uint32_t end_index = start_index + __items_per_page;
    if (end_index > __focus_obj_count) {
        end_index = __focus_obj_count;
    }
    uint32_t items_on_page = end_index - start_index;

    if (page_relative_index >= items_on_page) {
        page_relative_index = 0;
    }

    // show focus object (only if folder is not empty)
    if (__focus_obj_count > 0) {
        ui_floder_screen_keyboard_focus_show(page_relative_index);
    }

    return;
}

static void ui_floder_screen_keyboard_handler(lv_event_t * e)
{
    lv_key_t key = lv_event_get_key(e);

    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
            ui_floder_screen_keyboard_focus_prev();
            LV_LOG_USER("ui_floder_screen_keyboard_handler: UP or LEFT");
            break;
        case LV_KEY_PREV:
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
            ui_floder_screen_keyboard_focus_next();
            LV_LOG_USER("ui_floder_screen_keyboard_handler: DOWN or RIGHT");
            break;
        case LV_KEY_NEXT:
            break;
        case LV_KEY_ENTER:
            ui_floder_screen_keyboard_enter();
            LV_LOG_USER("ui_floder_screen_keyboard_handler: ENTER");
            break;
        case LV_KEY_ESC:
            ui_floder_screen_keyboard_esc();
            LV_LOG_USER("ui_floder_screen_keyboard_handler: ESC");
            break;
        default:
            break;
    }
}

/****************************** keyboard end ******************************/

/****************************** file list start ******************************/

/**
 * @brief Calculate how many items can fit per page dynamically
 *
 * This function calculates based on:
 * 1. Container height (ui_floder_screen_list_container)
 * 2. Item height (by creating a temporary item to measure)
 * 3. Flex layout gap/spacing
 *
 * @return Number of items that can fit on one page
 */
static uint32_t ui_floder_screen_calculate_items_per_page(void)
{
    if (!ui_floder_screen_list_container) {
        return 6;  // Default fallback value
    }

    // Ensure layout is updated before measuring
    lv_obj_update_layout(ui_floder_screen_list_container);

    // Get container height
    int32_t container_height = lv_obj_get_height(ui_floder_screen_list_container);

    // Create a temporary item to measure its height
    lv_obj_t *temp_item = ui_floder_item_container_create(ui_floder_screen_list_container);
    if (!temp_item) {
        return 6;  // Default fallback value
    }

    // Set a sample icon and label to get realistic height
    lv_image_set_src(ui_comp_get_child(temp_item, UI_COMP_FLODER_ITEM_CONTAINER_ICON),
                     &ui_img_image_floder_floder_32_png);
    lv_label_set_text(ui_comp_get_child(temp_item, UI_COMP_FLODER_ITEM_CONTAINER_LABEL),
                      "Sample");

    // Force layout update to get accurate measurements
    lv_obj_update_layout(temp_item);

    // Get item height (including padding)
    int32_t item_height = lv_obj_get_height(temp_item);

    // Get flex gap (spacing between items)
    int32_t flex_gap = lv_obj_get_style_pad_row(ui_floder_screen_list_container, LV_PART_MAIN);

    // Delete temporary item
    lv_obj_delete(temp_item);

    // Calculate items per page
    // Add flex_gap to item_height to account for spacing between items
    int32_t effective_item_height = item_height + flex_gap;

    uint32_t items_per_page = 1;  // At least 1 item
    if (effective_item_height > 0) {
        items_per_page = container_height / effective_item_height;
    }

    // Ensure at least 1 item per page, but reasonable maximum
    if (items_per_page < 1) {
        items_per_page = 1;
    } else if (items_per_page > 20) {
        // Sanity check: probably something wrong with measurement
        items_per_page = 6;  // Use default
    }

    LV_LOG_USER("Calculated items per page: %d (container: %d, item: %d, gap: %d)",
                items_per_page, container_height, item_height, flex_gap);

    return items_per_page;
}

static void ui_floder_screen_list_container_clear(void)
{
    if (!ui_floder_screen_list_container) {
        return;
    }
    lv_obj_clean(ui_floder_screen_list_container);
}

static const void *ui_floder_screen_file_list_get_icon(ui_fs_file_type_t type)
{
    switch (type) {
        case UI_FS_FILE_TYPE_DIRECTORY:
            return &ui_img_image_floder_floder_32_png;
        case UI_FS_FILE_TYPE_FILE_PNG:
            return &ui_img_image_floder_png_32_png;
        case UI_FS_FILE_TYPE_FILE_TEXT:
            return &ui_img_image_floder_txt_32_png;
        case UI_FS_FILE_TYPE_FILE_EPUB:
            return &ui_img_image_floder_epub_32_png;
        default:
            return &ui_img_image_floder_unkonwn_32_png;
    }
}

/**
 * @brief Render a specific page of the file list
 *
 * This function clears the container and displays only the items
 * for the specified page. Designed for e-paper displays to minimize
 * unnecessary redraws.
 *
 * @param page Page index to render (0-based)
 */
static void ui_floder_screen_file_list_render_page(uint32_t page)
{
    // Clear container first
    ui_floder_screen_list_container_clear();

    if (sg_file_list == NULL || sg_file_list->node_count == 0) {
        // Empty folder, just clear and return
        return;
    }

    // Validate page number
    if (page >= __total_pages) {
        page = __total_pages - 1;
    }

    // Calculate which items to display
    uint32_t start_index = page * __items_per_page;
    uint32_t end_index = start_index + __items_per_page;
    if (end_index > sg_file_list->node_count) {
        end_index = sg_file_list->node_count;
    }

    // Clear all user_data pointers first (UI objects will be deleted)
    ui_fs_file_node_t *node = sg_file_list->head;
    while (node != NULL) {
        node->user_data = NULL;
        node = (ui_fs_file_node_t *)node->next;
    }

    // Skip to start_index
    node = sg_file_list->head;
    for (uint32_t i = 0; i < start_index && node != NULL; i++) {
        node = (ui_fs_file_node_t *)node->next;
    }

    // Create UI items for current page
    for (uint32_t i = start_index; i < end_index && node != NULL; i++) {
        lv_obj_t *item = ui_floder_item_container_create(ui_floder_screen_list_container);
        lv_obj_set_x(item, 0);
        lv_obj_set_y(item, 0);

        // set icon
        const void *icon = ui_floder_screen_file_list_get_icon(node->type);
        lv_image_set_src(ui_comp_get_child(item, UI_COMP_FLODER_ITEM_CONTAINER_ICON), icon);

        // set label
        lv_label_set_text(ui_comp_get_child(item, UI_COMP_FLODER_ITEM_CONTAINER_LABEL), node->name);

        // set user data (link node to UI object)
        node->user_data = item;

        node = (ui_fs_file_node_t *)node->next;
    }

    // Update page info in status bar (optional - can show "Page 1/3")
    // LV_LOG_USER("Rendered page %d/%d (items %d-%d)", page + 1, __total_pages, start_index, end_index - 1);
}

/**
 * @brief Load file list from path and display first page
 *
 * @param path Directory path to list
 */
static void ui_floder_screen_file_list_show(const char *path)
{
    if (NULL == path) {
        return;
    }

    if (NULL != sg_file_list) {
        ui_fs_file_list_destroy(sg_file_list);
        sg_file_list = NULL;
    }

    int ui_rt = ui_fs_get_file_list(path, &sg_file_list);
    if (ui_rt != 0 || sg_file_list == NULL) {
        // No files found, reset pagination
        __focus_obj_count = 0;
        __current_page = 0;
        __total_pages = 0;
        ui_floder_screen_list_container_clear();
        return;
    }

    ui_fs_file_list_sort(sg_file_list);

    // Calculate items per page dynamically (only if not already calculated or container changed)
    if (__items_per_page == 0) {
        __items_per_page = ui_floder_screen_calculate_items_per_page();
    }

    // Update pagination info
    __focus_obj_count = sg_file_list->node_count;

    // Handle empty folder case
    if (__focus_obj_count == 0) {
        __total_pages = 0;
        __current_page = 0;
        __focus_obj_current_index = -1;  // No valid focus
        ui_floder_screen_file_list_render_page(0);  // Will show "Empty Folder" message
        LV_LOG_USER("Empty folder, no items to display");
        return;
    }

    // Calculate total pages for non-empty folder
    __total_pages = (__focus_obj_count + __items_per_page - 1) / __items_per_page;  // Ceiling division
    if (__total_pages == 0) {
        __total_pages = 1;
    }
    __current_page = 0;  // Start from first page

    // Render first page
    ui_floder_screen_file_list_render_page(__current_page);

    return;
}

/****************************** file list end ******************************/
