// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"
#include <stdint.h>

lv_obj_t * ui_home_screen = NULL;
lv_obj_t * ui_home_screen_status_bar = NULL;
lv_obj_t * ui_home_screen_battery = NULL;
lv_obj_t * ui_home_screen_title = NULL;
lv_obj_t * ui_home_screen_menu_container = NULL;
lv_obj_t * ui_home_screen_menu_floder = NULL;
lv_obj_t * ui_home_screen_menu_setting = NULL;
lv_obj_t * ui_home_screen_menu_badge = NULL;

/**************** extern keyboard group functions start ************************/

#define UI_HOME_FOCUS_OBJ_COUNT 3
#define INDEX_FLORDER 0
#define INDEX_SETTING 1
#define INDEX_BADGE 2

static lv_obj_t * __focus_obj_list[UI_HOME_FOCUS_OBJ_COUNT] = {NULL, NULL, NULL};
static int32_t __focus_obj_current_index = -1;

static lv_group_t *sg_keyboard_group = NULL;

static void ui_home_screen_keyboard_group_init(void);
static void ui_home_screen_keyboard_group_destroy(void);

static void ui_home_screen_keyboard_handler(lv_event_t * e);
/**************** extern keyboard group functions end ************************/

// event funtions
void ui_event_home_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_home_screen_loaded(e);

        // add keyboard group
        ui_home_screen_keyboard_group_init();
    } else if(event_code == LV_EVENT_KEY) {
        ui_home_screen_keyboard_handler(e);
    } else if(event_code == LV_EVENT_APP_BATTERY) {
        ui_battery_event_handler(ui_home_screen_battery);
    }
}

void ui_event_home_screen_menu_floder_menu_item_container(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_floder_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_floder_screen_screen_init);
    } else if (event_code == LV_EVENT_PRESSED) {
        // Only focus floder item container
        if (__focus_obj_current_index >= 0) {
            lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
        }
        __focus_obj_current_index = INDEX_FLORDER;
        lv_obj_send_event(__focus_obj_list[INDEX_FLORDER], LV_EVENT_FOCUSED, NULL);
    }
}

void ui_event_home_screen_menu_setting_menu_item_container(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setting_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_setting_screen_screen_init);
    } else if (event_code == LV_EVENT_PRESSED) {
        // Only focus setting item container
        if (__focus_obj_current_index >= 0) {
            lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
        }
        __focus_obj_current_index = INDEX_SETTING;
        lv_obj_send_event(__focus_obj_list[INDEX_SETTING], LV_EVENT_FOCUSED, NULL);
    }
}

void ui_event_home_screen_menu_badge_menu_item_container(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_badge_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_badge_screen_screen_init);
    } else if (event_code == LV_EVENT_PRESSED) {
        // Only focus badge item container
        if (__focus_obj_current_index >= 0) {
            lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
        }
        __focus_obj_current_index = INDEX_BADGE;
        lv_obj_send_event(__focus_obj_list[INDEX_BADGE], LV_EVENT_FOCUSED, NULL);
    }
}

// build funtions

void ui_home_screen_screen_init(void)
{
    ui_home_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_home_screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_home_screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_home_screen_status_bar = lv_obj_create(ui_home_screen);
    lv_obj_remove_style_all(ui_home_screen_status_bar);
    lv_obj_set_height(ui_home_screen_status_bar, 30);
    lv_obj_set_width(ui_home_screen_status_bar, lv_pct(100));
    lv_obj_set_x(ui_home_screen_status_bar, -1);
    lv_obj_set_y(ui_home_screen_status_bar, 0);
    lv_obj_set_align(ui_home_screen_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_home_screen_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_home_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_home_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_border_width(ui_home_screen_status_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_home_screen_status_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_home_screen_status_bar, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_battery = lv_image_create(ui_home_screen_status_bar);
    lv_image_set_src(ui_home_screen_battery, &ui_img_image_statue_bar_battery_battery_full_30_png);
    lv_obj_set_width(ui_home_screen_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_home_screen_battery, -10);
    lv_obj_set_y(ui_home_screen_battery, 0);
    lv_obj_set_align(ui_home_screen_battery, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_home_screen_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_home_screen_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_screen_title = lv_label_create(ui_home_screen_status_bar);
    lv_obj_set_width(ui_home_screen_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_home_screen_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_home_screen_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_screen_title, "Home");
    lv_obj_set_style_text_font(ui_home_screen_title, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_menu_container = lv_obj_create(ui_home_screen);
    lv_obj_remove_style_all(ui_home_screen_menu_container);
    lv_obj_set_height(ui_home_screen_menu_container, 270);
    lv_obj_set_width(ui_home_screen_menu_container, lv_pct(100));
    lv_obj_set_align(ui_home_screen_menu_container, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_home_screen_menu_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_home_screen_menu_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_home_screen_menu_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_screen_menu_floder = ui_menu_item_container_create(ui_home_screen_menu_container);
    lv_obj_set_x(ui_home_screen_menu_floder, 0);
    lv_obj_set_y(ui_home_screen_menu_floder, 0);

    lv_image_set_src(ui_comp_get_child(ui_home_screen_menu_floder, UI_COMP_MENU_ITEM_CONTAINER_IMG),
                     &ui_img_image_menu_folder_50_png);

    lv_label_set_text(ui_comp_get_child(ui_home_screen_menu_floder, UI_COMP_MENU_ITEM_CONTAINER_LABEL), "Floder");

    ui_home_screen_menu_setting = ui_menu_item_container_create(ui_home_screen_menu_container);
    lv_obj_set_x(ui_home_screen_menu_setting, 0);
    lv_obj_set_y(ui_home_screen_menu_setting, 0);

    lv_image_set_src(ui_comp_get_child(ui_home_screen_menu_setting, UI_COMP_MENU_ITEM_CONTAINER_IMG),
                     &ui_img_image_menu_setting_50_png);

    lv_label_set_text(ui_comp_get_child(ui_home_screen_menu_setting, UI_COMP_MENU_ITEM_CONTAINER_LABEL), "Setting");

    ui_home_screen_menu_badge = ui_menu_item_container_create(ui_home_screen_menu_container);
    lv_obj_set_x(ui_home_screen_menu_badge, 0);
    lv_obj_set_y(ui_home_screen_menu_badge, 0);

    lv_image_set_src(ui_comp_get_child(ui_home_screen_menu_badge, UI_COMP_MENU_ITEM_CONTAINER_IMG),
                     &ui_img_image_menu_badge_50_png);

    lv_label_set_text(ui_comp_get_child(ui_home_screen_menu_badge, UI_COMP_MENU_ITEM_CONTAINER_LABEL), "Badge");

    lv_obj_add_event_cb(ui_home_screen_menu_floder, ui_event_home_screen_menu_floder_menu_item_container, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_home_screen_menu_setting, ui_event_home_screen_menu_setting_menu_item_container, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_home_screen_menu_badge, ui_event_home_screen_menu_badge_menu_item_container, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_home_screen, ui_event_home_screen, LV_EVENT_ALL, NULL);

}

void ui_home_screen_screen_destroy(void)
{
    if(ui_home_screen) lv_obj_del(ui_home_screen);

    // NULL screen variables
    ui_home_screen = NULL;
    ui_home_screen_status_bar = NULL;
    ui_home_screen_battery = NULL;
    ui_home_screen_title = NULL;
    ui_home_screen_menu_container = NULL;
    ui_home_screen_menu_floder = NULL;
    ui_home_screen_menu_setting = NULL;
    ui_home_screen_menu_badge = NULL;

    ui_home_screen_keyboard_group_destroy();
}

/****************************** keyboard start ******************************/
static void ui_home_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        // add group to indev
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_home_screen_keyboard_group_init: failed to create group");
        return;
    }

    // add ui_home_screen to group
    lv_group_add_obj(sg_keyboard_group, ui_home_screen);

    // add focus objects
    __focus_obj_list[INDEX_FLORDER] = ui_home_screen_menu_floder;
    __focus_obj_list[INDEX_SETTING] = ui_home_screen_menu_setting;
    __focus_obj_list[INDEX_BADGE] = ui_home_screen_menu_badge;

    // add group to indev
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

static void ui_home_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

static void ui_home_screen_focus_prev(void)
{
    if (__focus_obj_current_index >= 0) {
        lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
    }

    __focus_obj_current_index--;
    if (__focus_obj_current_index < 0) {
        __focus_obj_current_index = UI_HOME_FOCUS_OBJ_COUNT - 1;
    }
    lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_FOCUSED, NULL);
}

static void ui_home_screen_focus_next(void)
{
    if (__focus_obj_current_index >= 0) {
        lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
    }

    __focus_obj_current_index++;
    if (__focus_obj_current_index >= UI_HOME_FOCUS_OBJ_COUNT) {
        __focus_obj_current_index = 0;
    }
    lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_FOCUSED, NULL);
}

static void ui_home_screen_keyboard_enter(void)
{
    if (__focus_obj_current_index < 0 || __focus_obj_current_index >= UI_HOME_FOCUS_OBJ_COUNT) {
        return;
    }

    lv_obj_t *focus_obj = __focus_obj_list[__focus_obj_current_index];

    lv_obj_send_event(focus_obj, LV_EVENT_CLICKED, NULL);
}

static void ui_home_screen_keyboard_handler(lv_event_t * e)
{
    lv_key_t key = lv_event_get_key(e);

    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
        case LV_KEY_PREV:
            ui_home_screen_focus_prev();
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
        case LV_KEY_NEXT:
            ui_home_screen_focus_next();
            break;
        case LV_KEY_ENTER:
            ui_home_screen_keyboard_enter();
            break;
        default:
            break;
    }
}

/****************************** keyboard end ******************************/
