// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"
#include <stdint.h>
#include "app_hardware.h"

lv_obj_t * ui_setting_screen = NULL;
lv_obj_t * ui_setting_screen_status_bar = NULL;
lv_obj_t * ui_setting_screen_battery = NULL;
lv_obj_t * ui_setting_screen_title = NULL;
lv_obj_t * ui_setting_screen_list_container = NULL;
lv_obj_t * ui_setting_screen_backlight = NULL;
lv_obj_t * ui_setting_screen_sleep_time = NULL;
lv_obj_t * ui_setting_screen_language = NULL;
/**************** extern keyboard group functions start ************************/
#define UI_SETTING_FOCUS_OBJ_COUNT 3
#define INDEX_BACKLIGHT 0
#define INDEX_SLEEP_TIME 1
#define INDEX_LANGUAGE 2

static lv_obj_t * __focus_obj_list[UI_SETTING_FOCUS_OBJ_COUNT] = {NULL, NULL, NULL};
static int32_t __focus_obj_current_index = 0;

static lv_group_t * sg_keyboard_group = NULL;

static void ui_setting_screen_keyboard_group_init(void);
static void ui_setting_screen_keyboard_group_destroy(void);

static void ui_setting_screen_keyboard_handler(lv_event_t * e);
/**************** extern keyboard group functions end ************************/
// event funtions
void ui_event_setting_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_setting_screen_loaded(e);

        // add keyboard group
        ui_setting_screen_keyboard_group_init();

        // Only focus first item
        if (__focus_obj_current_index >= 0) {
            lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
        }

        __focus_obj_current_index = INDEX_BACKLIGHT;
        lv_obj_send_event(__focus_obj_list[INDEX_BACKLIGHT], LV_EVENT_FOCUSED, NULL);
    } else if(event_code == LV_EVENT_KEY) {
        ui_setting_screen_keyboard_handler(e);
    } else if(event_code == LV_EVENT_APP_BATTERY) {
        ui_battery_event_handler(ui_setting_screen_battery);
    }
}

// build funtions

void ui_setting_screen_screen_init(void)
{
    ui_setting_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_screen_status_bar = lv_obj_create(ui_setting_screen);
    lv_obj_remove_style_all(ui_setting_screen_status_bar);
    lv_obj_set_height(ui_setting_screen_status_bar, 30);
    lv_obj_set_width(ui_setting_screen_status_bar, lv_pct(100));
    lv_obj_set_x(ui_setting_screen_status_bar, -1);
    lv_obj_set_y(ui_setting_screen_status_bar, 0);
    lv_obj_set_align(ui_setting_screen_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_setting_screen_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_setting_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_setting_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_foreground);
    lv_obj_set_style_border_width(ui_setting_screen_status_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_setting_screen_status_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting_screen_battery = lv_image_create(ui_setting_screen_status_bar);
    lv_image_set_src(ui_setting_screen_battery, &ui_img_image_statue_bar_battery_battery_full_30_png);
    lv_obj_set_width(ui_setting_screen_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setting_screen_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setting_screen_battery, -10);
    lv_obj_set_y(ui_setting_screen_battery, 0);
    lv_obj_set_align(ui_setting_screen_battery, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_setting_screen_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_setting_screen_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_screen_title = lv_label_create(ui_setting_screen_status_bar);
    lv_obj_set_width(ui_setting_screen_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setting_screen_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_setting_screen_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setting_screen_title, "Setting");
    lv_obj_set_style_text_font(ui_setting_screen_title, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting_screen_list_container = lv_obj_create(ui_setting_screen);
    lv_obj_remove_style_all(ui_setting_screen_list_container);
    lv_obj_set_height(ui_setting_screen_list_container, 270);
    lv_obj_set_width(ui_setting_screen_list_container, lv_pct(100));
    lv_obj_set_align(ui_setting_screen_list_container, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_setting_screen_list_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_screen_list_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_setting_screen_list_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_screen_backlight = ui_list_item_create(ui_setting_screen_list_container);
    lv_obj_set_x(ui_setting_screen_backlight, 0);
    lv_obj_set_y(ui_setting_screen_backlight, 0);

    lv_image_set_src(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_LEFT_ICON),
                     &ui_img_image_setting_light_32_png);

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_LEFT_LABEL), "Backlight");

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_RIGHT_OPTIONS), "ON");
    lv_obj_remove_flag(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_RIGHT_OPTIONS),
                       LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_setting_screen_sleep_time = ui_list_item_create(ui_setting_screen_list_container);
    lv_obj_set_x(ui_setting_screen_sleep_time, 0);
    lv_obj_set_y(ui_setting_screen_sleep_time, 0);

    lv_image_set_src(ui_comp_get_child(ui_setting_screen_sleep_time, UI_COMP_LIST_ITEM_LEFT_ICON),
                     &ui_img_image_setting_sleep_time_32_png);

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_sleep_time, UI_COMP_LIST_ITEM_LEFT_LABEL), "Sleep Time");

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_sleep_time, UI_COMP_LIST_ITEM_RIGHT_OPTIONS), "5 Min");
    lv_obj_remove_flag(ui_comp_get_child(ui_setting_screen_sleep_time, UI_COMP_LIST_ITEM_RIGHT_OPTIONS),
                       LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_setting_screen_language = ui_list_item_create(ui_setting_screen_list_container);
    lv_obj_set_x(ui_setting_screen_language, 0);
    lv_obj_set_y(ui_setting_screen_language, 0);

    lv_image_set_src(ui_comp_get_child(ui_setting_screen_language, UI_COMP_LIST_ITEM_LEFT_ICON),
                     &ui_img_image_setting_language_32_png);

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_language, UI_COMP_LIST_ITEM_LEFT_LABEL), "Language");

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_language, UI_COMP_LIST_ITEM_RIGHT_OPTIONS), "English");
    lv_obj_remove_flag(ui_comp_get_child(ui_setting_screen_language, UI_COMP_LIST_ITEM_RIGHT_OPTIONS),
                       LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_event_cb(ui_setting_screen, ui_event_setting_screen, LV_EVENT_ALL, NULL);

}

void ui_setting_screen_screen_destroy(void)
{
    if(ui_setting_screen) lv_obj_del(ui_setting_screen);

    // NULL screen variables
    ui_setting_screen = NULL;
    ui_setting_screen_status_bar = NULL;
    ui_setting_screen_battery = NULL;
    ui_setting_screen_title = NULL;
    ui_setting_screen_list_container = NULL;
    ui_setting_screen_backlight = NULL;
    ui_setting_screen_sleep_time = NULL;
    ui_setting_screen_language = NULL;

    ui_setting_screen_keyboard_group_destroy();
}

/****************************** keyboard start ******************************/
static void ui_setting_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        // add group to indev
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_setting_screen_keyboard_group_init: failed to create group");
        return;
    }

    // add ui_setting_screen to group
    lv_group_add_obj(sg_keyboard_group, ui_setting_screen);

    // add focus objects
    __focus_obj_list[INDEX_BACKLIGHT] = ui_setting_screen_backlight;
    __focus_obj_list[INDEX_SLEEP_TIME] = ui_setting_screen_sleep_time;
    __focus_obj_list[INDEX_LANGUAGE] = ui_setting_screen_language;

    // add group to indev
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

static void ui_setting_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

static void ui_setting_screen_focus_prev(void)
{
    if (__focus_obj_current_index >= 0) {
        lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
    }
    __focus_obj_current_index--;
    if (__focus_obj_current_index < 0) {
        __focus_obj_current_index = UI_SETTING_FOCUS_OBJ_COUNT - 1;
    }
    lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_FOCUSED, NULL);
}

static void ui_setting_screen_focus_next(void)
{
    if (__focus_obj_current_index >= 0) {
        lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
    }
    __focus_obj_current_index++;
    if (__focus_obj_current_index >= UI_SETTING_FOCUS_OBJ_COUNT) {
        __focus_obj_current_index = 0;
    }
    lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_FOCUSED, NULL);
}

static void ui_setting_screen_keyboard_enter(void)
{
    if (__focus_obj_current_index < 0 || __focus_obj_current_index >= UI_SETTING_FOCUS_OBJ_COUNT) {
        return;
    }
    lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_CLICKED, NULL);
}

static void ui_setting_screen_keyboard_handler(lv_event_t * e)
{
    lv_key_t key = lv_event_get_key(e);

    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
            ui_setting_screen_focus_prev();
            break;
        case LV_KEY_PREV:
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
            ui_setting_screen_focus_next();
            break;
        case LV_KEY_NEXT:
            break;
        case LV_KEY_ENTER:
            ui_setting_screen_keyboard_enter();
            break;
        case LV_KEY_ESC:
            _ui_screen_change(&ui_home_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_home_screen_screen_init);
            break;
        default:
            break;
    }
}

// option change callback functions
static void ui_setting_option_change_callback_backlight(lv_obj_t ** children)
{
    lv_obj_t * options = children[UI_COMP_LIST_ITEM_RIGHT_OPTIONS];
    const char * options_text = lv_label_get_text(options);

    if (strncmp(options_text, "ON", 2) == 0) {
        lv_label_set_text(options, "OFF");
        app_backlight_set_brightness(0);
    } else {
        lv_label_set_text(options, "ON");
        app_backlight_set_brightness(15);
    }
}

static void ui_setting_option_change_callback_sleep_time(lv_obj_t ** children)
{
    // 1 Min -> 3 Min -> 5 Min -> 15 Min -> 30 Min
    lv_obj_t * options = children[UI_COMP_LIST_ITEM_RIGHT_OPTIONS];
    const char * options_text = lv_label_get_text(options);

    if (strncmp(options_text, "1 Min", 5) == 0) {
        lv_label_set_text(options, "3 Min");
    } else if (strncmp(options_text, "3 Min", 5) == 0) {
        lv_label_set_text(options, "5 Min");
    } else if (strncmp(options_text, "5 Min", 5) == 0) {
        lv_label_set_text(options, "15 Min");
    }
    else if (strncmp(options_text, "15 Min", 7) == 0) {
        lv_label_set_text(options, "30 Min");
    } else {
        lv_label_set_text(options, "1 Min");
    }
}

static void ui_setting_option_change_callback_language(lv_obj_t ** children)
{
    // English -> Chinese

    lv_obj_t * options = children[UI_COMP_LIST_ITEM_RIGHT_OPTIONS];
    const char * options_text = lv_label_get_text(options);

    if (strncmp(options_text, "English", 7) == 0) {
        // TODO: Change language to Chinese
    } else {
        lv_label_set_text(options, "English");
    }
}

static void ui_setting_focus_obj_by_index(int32_t index)
{
    if (index == __focus_obj_current_index || index < 0 || index >= UI_SETTING_FOCUS_OBJ_COUNT) {
        return;
    }
    
    // Clear current focus object
    if (__focus_obj_current_index >= 0) {
        lv_obj_send_event(__focus_obj_list[__focus_obj_current_index], LV_EVENT_DEFOCUSED, NULL);
    }
    __focus_obj_current_index = index;
    lv_obj_send_event(__focus_obj_list[index], LV_EVENT_FOCUSED, NULL);
}

void ui_setting_option_change_callback(lv_event_t * e)
{
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);
    lv_obj_t * setting_item_container = children[UI_COMP_LIST_ITEM_LIST_ITEM];

    // Check if the currently focused object is the current setting item; if not, set it as the focused setting item
    if (setting_item_container != __focus_obj_list[__focus_obj_current_index]) {
        for (int i = 0; i < UI_SETTING_FOCUS_OBJ_COUNT; i++) {
            if (setting_item_container == __focus_obj_list[i]) {
                ui_setting_focus_obj_by_index(i);
                return;
            }
        }
    }

    // If the focused object is the current setting item, call the option change callback function
    if (setting_item_container == __focus_obj_list[__focus_obj_current_index]) {
        if (setting_item_container == ui_setting_screen_backlight) {
            ui_setting_option_change_callback_backlight(children);
        } else if (setting_item_container == ui_setting_screen_sleep_time) {
            ui_setting_option_change_callback_sleep_time(children);
        } else if (setting_item_container == ui_setting_screen_language) {
            ui_setting_option_change_callback_language(children);
        }
    }
}
/****************************** keyboard end ******************************/
