// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "ui.h"

void ui_home_screen_loaded(lv_event_t * e)
{
    (void)e; // Unused parameter
    // Your code here
    ui_battery_event_handler(ui_home_screen_battery);
}

void ui_home_menu_item_focused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);

    lv_obj_t * menu_item_container = children[UI_COMP_MENU_ITEM_CONTAINER_MENU_ITEM_CONTAINER];
    lv_obj_t * img = children[UI_COMP_MENU_ITEM_CONTAINER_IMG];
    lv_obj_t * label = children[UI_COMP_MENU_ITEM_CONTAINER_LABEL];

    lv_obj_set_style_bg_color(menu_item_container, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(menu_item_container, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_img_recolor(img, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_img_recolor_opa(img, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_text_color(label, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_opa(label, LV_OPA_100, LV_PART_MAIN);
}

void ui_home_menu_item_defocused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);

    lv_obj_t * menu_item_container = children[UI_COMP_MENU_ITEM_CONTAINER_MENU_ITEM_CONTAINER];
    lv_obj_t * img = children[UI_COMP_MENU_ITEM_CONTAINER_IMG];
    lv_obj_t * label = children[UI_COMP_MENU_ITEM_CONTAINER_LABEL];

    lv_obj_set_style_bg_color(menu_item_container, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(menu_item_container, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_img_recolor(img, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_img_recolor_opa(img, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_text_color(label, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_text_opa(label, LV_OPA_100, LV_PART_MAIN);
}

void ui_floder_screen_loaded(lv_event_t * e)
{
    (void)e; // Unused parameter
    // Your code here
    ui_battery_event_handler(ui_floder_screen_battery);
}

void ui_setting_screen_loaded(lv_event_t * e)
{
    (void)e; // Unused parameter
    // Your code here
    ui_battery_event_handler(ui_setting_screen_battery);
}

void ui_badge_screen_loaded(lv_event_t * e)
{
    (void)e; // Unused parameter
    // Your code here
}

void ui_file_screen_loaded(lv_event_t * e)
{
    (void)e; // Unused parameter
    // Your code here
}

void ui_floder_item_focused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);
    lv_obj_t * floder_item_container = children[UI_COMP_FLODER_ITEM_CONTAINER_FLODER_ITEM_CONTAINER];
    lv_obj_t * icon = children[UI_COMP_FLODER_ITEM_CONTAINER_ICON];
    lv_obj_t * label = children[UI_COMP_FLODER_ITEM_CONTAINER_LABEL];
    (void)icon;  // Unused variable
    (void)label; // Unused variable

    // add border to floder_item_container
    lv_obj_set_style_border_width(floder_item_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(floder_item_container, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(floder_item_container, LV_OPA_100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(floder_item_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(floder_item_container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_floder_item_defocused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);
    lv_obj_t * floder_item_container = children[UI_COMP_FLODER_ITEM_CONTAINER_FLODER_ITEM_CONTAINER];
    lv_obj_t * icon = children[UI_COMP_FLODER_ITEM_CONTAINER_ICON];
    lv_obj_t * label = children[UI_COMP_FLODER_ITEM_CONTAINER_LABEL];
    (void)icon;  // Unused variable
    (void)label; // Unused variable

    // remove border from floder_item_container
    lv_obj_set_style_border_width(floder_item_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(floder_item_container, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(floder_item_container, LV_OPA_0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(floder_item_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(floder_item_container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_setting_item_focused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);
    lv_obj_t * setting_item_container = children[UI_COMP_LIST_ITEM_LIST_ITEM];
    lv_obj_t * icon = children[UI_COMP_LIST_ITEM_LEFT_ICON];
    lv_obj_t * label = children[UI_COMP_LIST_ITEM_LEFT_LABEL];
    lv_obj_t * options = children[UI_COMP_LIST_ITEM_RIGHT_OPTIONS];
    (void)icon;    // Unused variable
    (void)label;   // Unused variable
    (void)options; // Unused variable

    // add border to floder_item_container
    lv_obj_set_style_border_width(setting_item_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(setting_item_container, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(setting_item_container, LV_OPA_100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(setting_item_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(setting_item_container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_setting_item_defocused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);
    lv_obj_t * setting_item_container = children[UI_COMP_LIST_ITEM_LIST_ITEM];
    lv_obj_t * icon = children[UI_COMP_LIST_ITEM_LEFT_ICON];
    lv_obj_t * label = children[UI_COMP_LIST_ITEM_LEFT_LABEL];
    lv_obj_t * options = children[UI_COMP_LIST_ITEM_RIGHT_OPTIONS];
    (void)icon;    // Unused variable
    (void)label;   // Unused variable
    (void)options; // Unused variable

    // remove border from setting_item_container
    lv_obj_set_style_border_width(setting_item_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(setting_item_container, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(setting_item_container, LV_OPA_0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(setting_item_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(setting_item_container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_setting_item_clicked_callback(lv_event_t * e)
{
    // Your code here
    // Call option change callback
    ui_setting_option_change_callback(e);
}
