// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_home_screen_loaded(lv_event_t * e);
void ui_home_menu_item_focused_callback(lv_event_t * e);
void ui_home_menu_item_defocused_callback(lv_event_t * e);
void ui_floder_screen_loaded(lv_event_t * e);
void ui_floder_item_focused_callback(lv_event_t * e);
void ui_floder_item_defocused_callback(lv_event_t * e);
void ui_setting_screen_loaded(lv_event_t * e);
void ui_setting_item_focused_callback(lv_event_t * e);
void ui_setting_item_defocused_callback(lv_event_t * e);
void ui_setting_item_clicked_callback(lv_event_t * e);
void ui_badge_screen_loaded(lv_event_t * e);
void ui_file_screen_loaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
