/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_CONDUCTING_H
#define GIF_CLAWD_CONDUCTING_H

#include "stdint.h"

extern const uint8_t *clawd_conducting_frames[];
extern const uint32_t clawd_conducting_frame_count;
extern const uint32_t clawd_conducting_delay_ms;
extern const uint32_t clawd_conducting_size;

#endif /* GIF_CLAWD_CONDUCTING_H */
