/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_IDLE_H
#define GIF_CLAWD_IDLE_H

#include "stdint.h"

extern const uint8_t *clawd_idle_frames[];
extern const uint32_t clawd_idle_frame_count;
extern const uint32_t clawd_idle_delay_ms;
extern const uint32_t clawd_idle_size;

#endif /* GIF_CLAWD_IDLE_H */
