/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_NOTIFICATION_H
#define GIF_CLAWD_NOTIFICATION_H

#include "stdint.h"

extern const uint8_t *clawd_notification_frames[];
extern const uint32_t clawd_notification_frame_count;
extern const uint32_t clawd_notification_delay_ms;
extern const uint32_t clawd_notification_size;

#endif /* GIF_CLAWD_NOTIFICATION_H */
