/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_ERROR_H
#define GIF_CLAWD_ERROR_H

#include "stdint.h"

extern const uint8_t *clawd_error_frames[];
extern const uint32_t clawd_error_frame_count;
extern const uint32_t clawd_error_delay_ms;
extern const uint32_t clawd_error_size;

#endif /* GIF_CLAWD_ERROR_H */
