/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_SWEEPING_H
#define GIF_CLAWD_SWEEPING_H

#include "stdint.h"

extern const uint8_t *clawd_sweeping_frames[];
extern const uint32_t clawd_sweeping_frame_count;
extern const uint32_t clawd_sweeping_delay_ms;
extern const uint32_t clawd_sweeping_size;

#endif /* GIF_CLAWD_SWEEPING_H */
