/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_SLEEPING_H
#define GIF_CLAWD_SLEEPING_H

#include "stdint.h"

extern const uint8_t *clawd_sleeping_frames[];
extern const uint32_t clawd_sleeping_frame_count;
extern const uint32_t clawd_sleeping_delay_ms;
extern const uint32_t clawd_sleeping_size;

#endif /* GIF_CLAWD_SLEEPING_H */
