/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_BUILDING_H
#define GIF_CLAWD_BUILDING_H

#include "stdint.h"

extern const uint8_t *clawd_building_frames[];
extern const uint32_t clawd_building_frame_count;
extern const uint32_t clawd_building_delay_ms;
extern const uint32_t clawd_building_size;

#endif /* GIF_CLAWD_BUILDING_H */
