/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_CARRYING_H
#define GIF_CLAWD_CARRYING_H

#include "stdint.h"

extern const uint8_t *clawd_carrying_frames[];
extern const uint32_t clawd_carrying_frame_count;
extern const uint32_t clawd_carrying_delay_ms;
extern const uint32_t clawd_carrying_size;

#endif /* GIF_CLAWD_CARRYING_H */
