/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_HAPPY_H
#define GIF_CLAWD_HAPPY_H

#include "stdint.h"

extern const uint8_t *clawd_happy_frames[];
extern const uint32_t clawd_happy_frame_count;
extern const uint32_t clawd_happy_delay_ms;
extern const uint32_t clawd_happy_size;

#endif /* GIF_CLAWD_HAPPY_H */
