/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_THINKING_H
#define GIF_CLAWD_THINKING_H

#include "stdint.h"

extern const uint8_t *clawd_thinking_frames[];
extern const uint32_t clawd_thinking_frame_count;
extern const uint32_t clawd_thinking_delay_ms;
extern const uint32_t clawd_thinking_size;

#endif /* GIF_CLAWD_THINKING_H */
