/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_TYPING_H
#define GIF_CLAWD_TYPING_H

#include "stdint.h"

extern const uint8_t *clawd_typing_frames[];
extern const uint32_t clawd_typing_frame_count;
extern const uint32_t clawd_typing_delay_ms;
extern const uint32_t clawd_typing_size;

#endif /* GIF_CLAWD_TYPING_H */
