/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_DEBUGGER_H
#define GIF_CLAWD_DEBUGGER_H

#include "stdint.h"

extern const uint8_t *clawd_debugger_frames[];
extern const uint32_t clawd_debugger_frame_count;
extern const uint32_t clawd_debugger_delay_ms;
extern const uint32_t clawd_debugger_size;

#endif /* GIF_CLAWD_DEBUGGER_H */
