/* Auto-generated by gif_to_c.py — DO NOT EDIT */
#ifndef GIF_CLAWD_JUGGLING_H
#define GIF_CLAWD_JUGGLING_H

#include "stdint.h"

extern const uint8_t *clawd_juggling_frames[];
extern const uint32_t clawd_juggling_frame_count;
extern const uint32_t clawd_juggling_delay_ms;
extern const uint32_t clawd_juggling_size;

#endif /* GIF_CLAWD_JUGGLING_H */
