// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef _UI_COMP_FLODER_ITEM_CONTAINER_H
#define _UI_COMP_FLODER_ITEM_CONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT floder item container
#define UI_COMP_FLODER_ITEM_CONTAINER_FLODER_ITEM_CONTAINER 0
#define UI_COMP_FLODER_ITEM_CONTAINER_ICON 1
#define UI_COMP_FLODER_ITEM_CONTAINER_LABEL 2
#define _UI_COMP_FLODER_ITEM_CONTAINER_NUM 3
lv_obj_t * ui_floder_item_container_create(lv_obj_t * comp_parent);
void ui_event_comp_floder_item_container_floder_item_container(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
