// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef _UI_COMP_LIST_ITEM_H
#define _UI_COMP_LIST_ITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT list item
#define UI_COMP_LIST_ITEM_LIST_ITEM 0
#define UI_COMP_LIST_ITEM_LEFT 1
#define UI_COMP_LIST_ITEM_LEFT_ICON 2
#define UI_COMP_LIST_ITEM_LEFT_LABEL 3
#define UI_COMP_LIST_ITEM_RIGHT 4
#define UI_COMP_LIST_ITEM_RIGHT_OPTIONS 5
#define _UI_COMP_LIST_ITEM_NUM 6
lv_obj_t * ui_list_item_create(lv_obj_t * comp_parent);
void ui_event_comp_list_item_list_item(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
