// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

void ui_event_comp_floder_item_container_floder_item_container(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_floder_item_container = lv_event_get_user_data(e);
    (void)comp_floder_item_container; // Unused variable

    if(event_code == LV_EVENT_FOCUSED) {
        ui_floder_item_focused_callback(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ui_floder_item_defocused_callback(e);
    }
}

// COMPONENT floder item container

lv_obj_t * ui_floder_item_container_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_floder_item_container;
    cui_floder_item_container = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_floder_item_container);
    lv_obj_set_width(cui_floder_item_container, lv_pct(100));
    lv_obj_set_height(cui_floder_item_container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_floder_item_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_floder_item_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_floder_item_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_floder_item_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_floder_item_container, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(cui_floder_item_container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_foreground);

    lv_obj_set_style_border_width(cui_floder_item_container, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_floder_item_container, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_floder_item_container, LV_OPA_0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_floder_item_container, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_floder_item_container, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(cui_floder_item_container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_floder_item_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_floder_item_container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_floder_item_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_icon;
    cui_icon = lv_image_create(cui_floder_item_container);
    lv_obj_set_width(cui_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(cui_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_label;
    cui_label = lv_label_create(cui_floder_item_container);
    lv_obj_set_width(cui_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label, "Name");
    lv_obj_add_flag(cui_label, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_font(cui_label, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_FLODER_ITEM_CONTAINER_NUM);
    children[UI_COMP_FLODER_ITEM_CONTAINER_FLODER_ITEM_CONTAINER] = cui_floder_item_container;
    children[UI_COMP_FLODER_ITEM_CONTAINER_ICON] = cui_icon;
    children[UI_COMP_FLODER_ITEM_CONTAINER_LABEL] = cui_label;
    lv_obj_add_event_cb(cui_floder_item_container, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_floder_item_container, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_floder_item_container, ui_event_comp_floder_item_container_floder_item_container, LV_EVENT_ALL,
                        children);
    ui_comp_floder_item_container_create_hook(cui_floder_item_container);
    return cui_floder_item_container;
}
