// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef _E_PAPER_UI_COMP_HOOK_H
#define _E_PAPER_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_floder_item_container_create_hook(lv_obj_t * comp);
void ui_comp_list_item_create_hook(lv_obj_t * comp);
void ui_comp_menu_item_container_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
