/**
 * @file buddy_fsm.c
 * @brief Buddy state machine and pixel animations.
 *
 * Each state plays a GIF animation via the board_pixel_gif API.
 * The BUSY state cycles through 7 "work" GIFs on each entry so the
 * display stays interesting across multiple Claude sessions.
 *
 * GIF → state mapping:
 *   DISCONNECTED : clawd-sleeping
 *   IDLE         : clawd-idle
 *   BUSY (cycle) : building / carrying / conducting / debugger /
 *                  sweeping / thinking / typing  (7 animations)
 *   ATTENTION    : clawd-notification
 *   CELEBRATE    : clawd-happy  (odd entries) / clawd-juggling (even)
 *   DIZZY        : clawd-conducting
 *
 * @copyright Copyright (c) 2021-2025 Tuya Inc. All Rights Reserved.
 */

#include "buddy_fsm.h"
#include "board_pixel_api.h"
#include "tdl_pixel_dev_manage.h"
#include "tdl_pixel_color_manage.h"
#include "tal_log.h"
#include "tal_system.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>

/* GIF data arrays (auto-generated by gif_to_c.py) */
#include "claude_status_gif/gif_clawd_sleeping.h"
#include "claude_status_gif/gif_clawd_idle.h"
#include "claude_status_gif/gif_clawd_building.h"
#include "claude_status_gif/gif_clawd_typing.h"
#include "claude_status_gif/gif_clawd_notification.h"
#include "claude_status_gif/gif_clawd_error.h"
#include "claude_status_gif/gif_clawd_happy.h"
#include "claude_status_gif/gif_clawd_juggling.h"
#include "claude_status_gif/gif_clawd_conducting.h"

/***********************************************************
 * Constants
 ***********************************************************/
#define MATRIX_W       32
#define MATRIX_H       32
#define PIXEL_TOTAL    (MATRIX_W * MATRIX_H + 3)
#define COLOR_RES      1000u
#define BRIGHTNESS     0.05f

#define DIZZY_TIMEOUT_TICKS      (3000  / BUDDY_RENDER_INTERVAL_MS)
#define CELEBRATE_TIMEOUT_TICKS  (8000  / BUDDY_RENDER_INTERVAL_MS)
#define ATTENTION_TIMEOUT_TICKS  (60000 / BUDDY_RENDER_INTERVAL_MS)

/***********************************************************
 * BUSY GIF pool  (building / typing, alternating)
 ***********************************************************/
#define BUSY_POOL_SIZE  2u

/***********************************************************
 * Internal state
 ***********************************************************/
static PIXEL_HANDLE_T       s_px    = NULL;
static PIXEL_FRAME_HANDLE_T s_frame = NULL;

/* One GIF handle per state */
static PIXEL_GIF_HANDLE_T   s_gif_disconnected = NULL;
static PIXEL_GIF_HANDLE_T   s_gif_idle         = NULL;
static PIXEL_GIF_HANDLE_T   s_gif_busy         = NULL; /* points into pool */
static PIXEL_GIF_HANDLE_T   s_gif_attention    = NULL;
static PIXEL_GIF_HANDLE_T   s_gif_celebrate    = NULL;
static PIXEL_GIF_HANDLE_T   s_gif_dizzy        = NULL;

/* BUSY pool */
static PIXEL_GIF_HANDLE_T   s_busy_handles[BUSY_POOL_SIZE];
static uint32_t             s_busy_idx = 0;

/* CELEBRATE alternates between happy and juggling */
static PIXEL_GIF_HANDLE_T   s_gif_happy    = NULL;
static PIXEL_GIF_HANDLE_T   s_gif_juggling = NULL;
static uint32_t             s_celebrate_idx = 0;

static buddy_state_e        s_state       = BUDDY_STATE_DISCONNECTED;
static buddy_state_e        s_pre_dizzy   = BUDDY_STATE_DISCONNECTED;
static buddy_state_info_t   s_info        = {0};
static uint32_t             s_tick            = 0;
static uint32_t             s_dizzy_ticks     = 0;
static uint32_t             s_celebrate_ticks = 0;
static uint32_t             s_attention_ticks = 0;

/***********************************************************
 * Helpers
 ***********************************************************/
static inline void px_clear(void)
{
    PIXEL_COLOR_T off = {0};
    tdl_pixel_set_single_color(s_px, 0, PIXEL_TOTAL, &off);
}

static inline void px_flush(void)
{
    tdl_pixel_dev_refresh(s_px);
}

/** Create one GIF handle; logs a warning on failure (non-fatal). */
static PIXEL_GIF_HANDLE_T make_gif(const uint8_t **frames, uint32_t count,
                                    uint32_t size, uint32_t delay_ms,
                                    const char *name)
{
    PIXEL_GIF_HANDLE_T h = board_pixel_gif_create(
        frames, count, size, size, delay_ms);
    if (!h) {
        PR_WARN("buddy_fsm: gif_create failed for %s", name);
    }
    return h;
}

/** Play current frame of a GIF into the frame buffer and advance. */
static void play_gif(PIXEL_GIF_HANDLE_T gif)
{
    if (!s_frame || !gif) {
        /* fallback: dim pulse */
        float brt = 0.003f + 0.002f * sinf(s_tick * 0.08f);
        uint32_t v = (uint32_t)(brt * COLOR_RES);
        PIXEL_COLOR_T c = {.red = v, .green = v, .blue = v};
        tdl_pixel_set_single_color(s_px, 0, PIXEL_TOTAL, &c);
        px_flush();
        return;
    }
    board_pixel_frame_clear(s_frame);
    board_pixel_draw_gif(s_frame, gif, 0, 0);
    board_pixel_frame_render(s_frame);
}

/***********************************************************
 * Per-state renderers
 ***********************************************************/
static void render_disconnected(void) { play_gif(s_gif_disconnected); }
static void render_idle(void)         { play_gif(s_gif_idle);         }
static void render_busy(void)         { play_gif(s_gif_busy);         }
static void render_attention(void)    { play_gif(s_gif_attention);    }
static void render_celebrate(void)    { play_gif(s_gif_celebrate);    }
static void render_dizzy(void)        { play_gif(s_gif_dizzy);        }

/***********************************************************
 * Public API
 ***********************************************************/

OPERATE_RET buddy_fsm_init(void)
{
    OPERATE_RET rt = board_pixel_get_handle(&s_px);
    if (rt != OPRT_OK || s_px == NULL) {
        PR_ERR("buddy_fsm: failed to get pixel handle: %d", rt);
        return rt;
    }

    s_frame = board_pixel_frame_create();
    if (!s_frame) {
        PR_WARN("buddy_fsm: frame create failed — GIF rendering disabled");
    }

    /* --- Static state GIFs --- */
    s_gif_disconnected = make_gif(clawd_sleeping_frames,
                                   clawd_sleeping_frame_count,
                                   clawd_sleeping_size,
                                   clawd_sleeping_delay_ms, "sleeping");

    s_gif_idle         = make_gif(clawd_idle_frames,
                                   clawd_idle_frame_count,
                                   clawd_idle_size,
                                   clawd_idle_delay_ms, "idle");

    s_gif_attention    = make_gif(clawd_notification_frames,
                                   clawd_notification_frame_count,
                                   clawd_notification_size,
                                   clawd_notification_delay_ms, "notification");

    s_gif_happy        = make_gif(clawd_happy_frames,
                                   clawd_happy_frame_count,
                                   clawd_happy_size,
                                   clawd_happy_delay_ms, "happy");

    s_gif_juggling     = make_gif(clawd_juggling_frames,
                                   clawd_juggling_frame_count,
                                   clawd_juggling_size,
                                   clawd_juggling_delay_ms, "juggling");

    s_gif_dizzy        = make_gif(clawd_conducting_frames,
                                   clawd_conducting_frame_count,
                                   clawd_conducting_size,
                                   clawd_conducting_delay_ms, "conducting");

    /* --- BUSY pool (building / typing, alternating) --- */
    s_busy_handles[0]  = make_gif(clawd_building_frames,
                                   clawd_building_frame_count,
                                   clawd_building_size,
                                   clawd_building_delay_ms, "building");
    s_busy_handles[1]  = make_gif(clawd_typing_frames,
                                   clawd_typing_frame_count,
                                   clawd_typing_size,
                                   clawd_typing_delay_ms, "typing");

    /* Start with first BUSY GIF */
    s_gif_busy     = s_busy_handles[0];
    s_gif_celebrate = s_gif_happy;

    s_state = BUDDY_STATE_DISCONNECTED;
    s_tick  = 0;
    PR_NOTICE("buddy_fsm: initialized (%u BUSY GIFs)", (unsigned)BUSY_POOL_SIZE);
    return OPRT_OK;
}

void buddy_fsm_set_state(const buddy_state_info_t *info)
{
    if (!info) return;

    if (s_state == BUDDY_STATE_DIZZY) {
        memcpy(&s_info, info, sizeof(s_info));
        s_pre_dizzy = info->state;
        return;
    }

    if (info->state != s_state) {
        PR_NOTICE("buddy_fsm: state %d -> %d", s_state, info->state);
        s_tick = 0;

        switch (info->state) {
        case BUDDY_STATE_BUSY:
            /* Advance to next BUSY GIF in pool */
            s_busy_idx = (s_busy_idx + 1) % BUSY_POOL_SIZE;
            s_gif_busy = s_busy_handles[s_busy_idx];
            if (s_gif_busy) board_pixel_gif_reset(s_gif_busy);
            PR_NOTICE("buddy_fsm: BUSY gif[%u]", (unsigned)s_busy_idx);
            break;

        case BUDDY_STATE_CELEBRATE:
            /* Alternate between happy and juggling */
            s_celebrate_idx++;
            s_gif_celebrate = (s_celebrate_idx % 2 == 0) ? s_gif_happy : s_gif_juggling;
            if (s_gif_celebrate) board_pixel_gif_reset(s_gif_celebrate);
            s_celebrate_ticks = 0;
            break;

        case BUDDY_STATE_ATTENTION:
            if (s_gif_attention) board_pixel_gif_reset(s_gif_attention);
            s_attention_ticks = 0;
            break;

        case BUDDY_STATE_IDLE:
            if (s_gif_idle) board_pixel_gif_reset(s_gif_idle);
            break;

        case BUDDY_STATE_DISCONNECTED:
            if (s_gif_disconnected) board_pixel_gif_reset(s_gif_disconnected);
            break;

        default:
            break;
        }
    }

    s_state = info->state;
    memcpy(&s_info, info, sizeof(s_info));
}

buddy_state_e buddy_fsm_get_state(void)
{
    return s_state;
}

void buddy_fsm_trigger_dizzy(void)
{
    if (s_state != BUDDY_STATE_DIZZY) {
        s_pre_dizzy = s_state;
    }
    s_state       = BUDDY_STATE_DIZZY;
    s_dizzy_ticks = 0;
    s_tick        = 0;
    if (s_gif_dizzy) board_pixel_gif_reset(s_gif_dizzy);
    PR_NOTICE("buddy_fsm: DIZZY triggered");
}

void buddy_fsm_render_tick(void)
{
    if (s_px == NULL) return;

    if (s_state == BUDDY_STATE_DIZZY) {
        s_dizzy_ticks++;
        if (s_dizzy_ticks >= DIZZY_TIMEOUT_TICKS) {
            s_state = s_pre_dizzy;
            s_tick  = 0;
            PR_NOTICE("buddy_fsm: DIZZY -> %d", s_state);
        }
    }

    if (s_state == BUDDY_STATE_CELEBRATE) {
        s_celebrate_ticks++;
        if (s_celebrate_ticks >= CELEBRATE_TIMEOUT_TICKS) {
            s_state = BUDDY_STATE_IDLE;
            s_tick  = 0;
            if (s_gif_idle) board_pixel_gif_reset(s_gif_idle);
            PR_NOTICE("buddy_fsm: CELEBRATE -> IDLE (timeout)");
        }
    }

    if (s_state == BUDDY_STATE_ATTENTION) {
        s_attention_ticks++;
        if (s_attention_ticks >= ATTENTION_TIMEOUT_TICKS) {
            s_state = BUDDY_STATE_IDLE;
            s_tick  = 0;
            if (s_gif_idle) board_pixel_gif_reset(s_gif_idle);
            PR_NOTICE("buddy_fsm: ATTENTION -> IDLE (timeout)");
        }
    }

    switch (s_state) {
    case BUDDY_STATE_DISCONNECTED: render_disconnected(); break;
    case BUDDY_STATE_IDLE:         render_idle();         break;
    case BUDDY_STATE_BUSY:         render_busy();         break;
    case BUDDY_STATE_ATTENTION:    render_attention();    break;
    case BUDDY_STATE_CELEBRATE:    render_celebrate();    break;
    case BUDDY_STATE_DIZZY:        render_dizzy();        break;
    default:                       render_disconnected(); break;
    }

    s_tick++;
}
