#!/usr/bin/env python3
"""
gif_to_c.py — Convert a GIF animation to a C array for the 32×32 LED matrix.

Color handling:
  - Transparent pixels are composited onto a BLACK background so that
    background LEDs stay off (transparent = no light).
  - Two-pass BOX (area-averaging) resampling for large downscales reduces the
    colour shift / ringing that LANCZOS produces at very small output sizes.
  - Raw 0-255 pixel values are stored in the C array (--brightness default 1.0).
    board_pixel_draw_bitmap() in the firmware already applies its own
    BRIGHTNESS * COLOR_RESOLUTION / 255 scaling (~20%), so do NOT bake an
    additional brightness reduction here or the output will be extremely dim
    (0.1 * 0.2 = 2% of original — that is why colours look wrong / too dim).

Usage:
  python gif_to_c.py <input.gif> [--brightness 1.0] [--size 32] [-o output.c]
"""

import argparse
import os
import sys

try:
    from PIL import Image, ImageEnhance
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow", file=sys.stderr)
    sys.exit(1)


def _improved_resize(frame: Image.Image, w: int, h: int) -> Image.Image:
    """
    Two-pass BOX downscale identical to tool_pixel_art_gen.py improved_resize().
    For scale < 0.5 (e.g. 200→32 = 0.16) first shrink to 2× target then BOX again.
    """
    ow, oh = frame.size
    sx = w / ow
    sy = h / oh
    if sx < 0.5 or sy < 0.5:
        iw = max(w * 2, ow // 2)
        ih = max(h * 2, oh // 2)
        frame = frame.resize((iw, ih), Image.Resampling.BOX)
    return frame.resize((w, h), Image.Resampling.BOX)


def _frame_to_rgb(img: Image.Image) -> Image.Image:
    """
    Convert one GIF frame to RGB on a WHITE background (same as reference script).
    Handles palette ('P'), RGBA and RGB modes.
    """
    if img.mode == 'P':
        img = img.convert('RGBA')

    if img.mode == 'RGBA':
        bg = Image.new('RGB', img.size, (0, 0, 0))
        bg.paste(img, mask=img.split()[3])   # alpha mask
        return bg
    elif img.mode in ('LA', 'L'):
        bg = Image.new('RGB', img.size, (0, 0, 0))
        bg.paste(img.convert('RGB'))
        return bg
    else:
        return img.convert('RGB')


def gif_to_c(gif_path: str, brightness: float = 1.0, size: int = 32,
             saturation: float = 2.0) -> str:
    img = Image.open(gif_path)
    basename = os.path.splitext(os.path.basename(gif_path))[0]
    varname  = basename.replace('-', '_').replace(' ', '_')

    frames_data: list[list[int]] = []
    durations:   list[int]       = []

    idx = 0
    while True:
        try:
            img.seek(idx)
        except EOFError:
            break

        rgb = _frame_to_rgb(img)
        scaled = _improved_resize(rgb, size, size)

        # Boost saturation so colours stay vivid at the ~5% LED drive level.
        # board_pixel_draw_bitmap applies ×0.05 scaling; at that level low-
        # saturation colours (e.g. salmon) look pink due to LED non-linearity.
        # A 2× boost pushes salmon → vivid orange, peach → warm orange, etc.
        if saturation != 1.0:
            scaled = ImageEnhance.Color(scaled).enhance(saturation)

        # Apply brightness after resize (keeps colour ratios intact)
        pixels = scaled.tobytes()          # flat R,G,B bytes
        frame: list[int] = []
        for i in range(0, len(pixels), 3):
            frame.append(min(255, int(pixels[i]     * brightness)))
            frame.append(min(255, int(pixels[i + 1] * brightness)))
            frame.append(min(255, int(pixels[i + 2] * brightness)))

        frames_data.append(frame)
        durations.append(img.info.get('duration', 100))
        idx += 1

    n_frames     = len(frames_data)
    avg_delay_ms = sum(durations) // len(durations)
    bpf          = size * size * 3          # bytes per frame

    lines: list[str] = []
    lines += [
        f"/* Auto-generated by gif_to_c.py — DO NOT EDIT */",
        f"/* Source   : {os.path.basename(gif_path)} */",
        f"/* Frames   : {n_frames} */",
        f"/* Size     : {size}x{size} px */",
        f"/* Delay    : ~{avg_delay_ms} ms/frame */",
        f"/* Brightness: {brightness} */",
        "",
        '#include "stdint.h"',
        f'#include "gif_{varname}.h"',
        "",
    ]

    for i, frame in enumerate(frames_data):
        lines.append(f"static const uint8_t s_f{i:03d}[{bpf}] = {{")
        row_bytes = size * 3
        for row in range(size):
            s = row * row_bytes
            chunk = frame[s:s + row_bytes]
            lines.append("  " + ",".join(f"0x{b:02X}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")

    lines.append(f"const uint8_t *{varname}_frames[{n_frames}] = {{")
    for i in range(n_frames):
        lines.append(f"  s_f{i:03d},")
    lines.append("};")
    lines.append("")
    lines.append(f"const uint32_t {varname}_frame_count = {n_frames};")
    lines.append(f"const uint32_t {varname}_delay_ms    = {avg_delay_ms};")
    lines.append(f"const uint32_t {varname}_size        = {size};")
    lines.append("")

    return "\n".join(lines)


def make_header(gif_path: str) -> str:
    basename = os.path.splitext(os.path.basename(gif_path))[0]
    varname  = basename.replace('-', '_').replace(' ', '_')
    guard    = f"GIF_{varname.upper()}_H"
    return "\n".join([
        f"/* Auto-generated by gif_to_c.py — DO NOT EDIT */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "stdint.h"',
        "",
        f"extern const uint8_t *{varname}_frames[];",
        f"extern const uint32_t {varname}_frame_count;",
        f"extern const uint32_t {varname}_delay_ms;",
        f"extern const uint32_t {varname}_size;",
        "",
        f"#endif /* {guard} */",
        "",
    ])


def main():
    parser = argparse.ArgumentParser(description="Convert GIF → C array for LED matrix")
    parser.add_argument("input",               help="Input GIF file")
    parser.add_argument("--brightness", "-b",  type=float, default=1.0,
                        help="LED brightness multiplier 0.0-1.0 (default 1.0; "
                             "board_pixel_draw_bitmap already applies ~5%% scaling)")
    parser.add_argument("--saturation", "-S",  type=float, default=2.0,
                        help="Colour saturation boost (default 2.0; compensates for "
                             "LED non-linearity at low drive levels)")
    parser.add_argument("--size",       "-s",  type=int,   default=32,
                        help="Output frame size in pixels (default 32)")
    parser.add_argument("--output",     "-o",              default=None,
                        help="Output .c file (default: src/gif_<name>.c)")
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"ERROR: file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    c_code = gif_to_c(args.input, args.brightness, args.size, args.saturation)

    basename = os.path.splitext(os.path.basename(args.input))[0]
    varname  = basename.replace('-', '_')

    c_path = args.output or os.path.join(
        os.path.dirname(args.input) or ".", f"gif_{varname}.c")
    h_path = os.path.splitext(c_path)[0] + ".h"

    with open(c_path, 'w') as f:
        f.write(c_code)
    with open(h_path, 'w') as f:
        f.write(make_header(args.input))

    # Quick stats
    img = Image.open(args.input)
    n, dur = 0, []
    while True:
        try:
            img.seek(n); dur.append(img.info.get('duration', 100)); n += 1
        except EOFError:
            break

    print(f"Generated: {c_path}")
    print(f"Generated: {h_path}")
    print(f"  {n} frames, ~{sum(dur)//len(dur)} ms/frame, "
          f"{args.size}x{args.size}px, brightness={args.brightness}")


if __name__ == '__main__':
    main()
