// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef _E_PAPER_UI_H
#define _E_PAPER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home_screen.h"
#include "screens/ui_floder_screen.h"
#include "screens/ui_setting_screen.h"
#include "screens/ui_badge_screen.h"
#include "screens/ui_file_screen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_image_statue_bar_battery_battery_full_30_png);    // assets/image/statue_bar/battery/battery_full_30.png
LV_IMG_DECLARE(ui_img_image_menu_folder_50_png);    // assets/image/menu/folder_50.png
LV_IMG_DECLARE(ui_img_image_menu_setting_50_png);    // assets/image/menu/setting_50.png
LV_IMG_DECLARE(ui_img_image_menu_badge_50_png);    // assets/image/menu/badge_50.png
LV_IMG_DECLARE(ui_img_image_statue_bar_sd_tf_30_png);    // assets/image/statue_bar/sd/tf_30.png
LV_IMG_DECLARE(ui_img_image_floder_floder_32_png);    // assets/image/floder/floder_32.png
LV_IMG_DECLARE(ui_img_image_floder_txt_32_png);    // assets/image/floder/txt_32.png
LV_IMG_DECLARE(ui_img_image_floder_png_32_png);    // assets/image/floder/png_32.png
LV_IMG_DECLARE(ui_img_image_floder_epub_32_png);    // assets/image/floder/epub_32.png
LV_IMG_DECLARE(ui_img_image_setting_light_32_png);    // assets/image/setting/light_32.png
LV_IMG_DECLARE(ui_img_image_setting_sleep_time_32_png);    // assets/image/setting/sleep_time_32.png
LV_IMG_DECLARE(ui_img_image_setting_language_32_png);    // assets/image/setting/language_32.png
LV_IMG_DECLARE(ui_img_image_badge_nfc_32_png);    // assets/image/badge/nfc_32.png
LV_IMG_DECLARE(ui_img_image_badge_tuyaopen_logo_png);    // assets/image/badge/tuyaopen_logo.png
LV_IMG_DECLARE(ui_img_image_badge_tuyaopen_qr_48_png);    // assets/image/badge/tuyaopen_qr_48.png
LV_IMG_DECLARE(ui_img_image_floder_wallpaper_png);    // assets/image/floder/wallpaper.png
LV_IMG_DECLARE(
    ui_img_image_statue_bar_battery_battery_60_30_png);    // assets/image/statue_bar/battery/battery_60_30.png
LV_IMG_DECLARE(
    ui_img_image_statue_bar_battery_battery_charging_30_png);    // assets/image/statue_bar/battery/battery_charging_30.png
LV_IMG_DECLARE(
    ui_img_image_statue_bar_battery_battery_empty_30_png);    // assets/image/statue_bar/battery/battery_empty_30.png
LV_IMG_DECLARE(
    ui_img_image_statue_bar_battery_battery_low_30_png);    // assets/image/statue_bar/battery/battery_low_30.png

// FONTS
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_12_1);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_12_2);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_12_4);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_14_2);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_18_1);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_24_4);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Regular_12_1);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Regular_14_2);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Regular_16_2);
LV_FONT_DECLARE(ui_font_puhui_48);
LV_FONT_DECLARE(ui_font_terminus_bold_16_2);
LV_FONT_DECLARE(ui_font_terminus_bold_18_2);
LV_FONT_DECLARE(ui_font_terminus_bold_24_4);
LV_FONT_DECLARE(ui_font_terminus_bold_14_2);
LV_FONT_DECLARE(ui_font_terminus_bold_16_1);
LV_FONT_DECLARE(ui_font_terminus_bold_14_1);
LV_FONT_DECLARE(ui_font_terminus_bold_32_2);
LV_FONT_DECLARE(ui_font_JetBrains_Mono_Bold_32_4);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
