// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "ui.h"

void home_screen_loaded(lv_event_t * e)
{
    // Your code here
    (void)e;
}

void ui_home_screen_loaded(lv_event_t * e)
{
    // Your code here
    (void)e;
}

void ui_home_menu_item_focused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);

    lv_obj_t * menu_item_container = children[UI_COMP_MENU_ITEM_CONTAINER_MENU_ITEM_CONTAINER];
    lv_obj_t * img = children[UI_COMP_MENU_ITEM_CONTAINER_IMG];
    lv_obj_t * label = children[UI_COMP_MENU_ITEM_CONTAINER_LABEL];

    lv_obj_set_style_bg_color(menu_item_container, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(menu_item_container, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_img_recolor(img, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_img_recolor_opa(img, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_text_color(label, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_opa(label, LV_OPA_100, LV_PART_MAIN);
}

void ui_home_menu_item_defocused_callback(lv_event_t * e)
{
    // Your code here
    lv_obj_t ** children = (lv_obj_t **)lv_event_get_user_data(e);

    lv_obj_t * menu_item_container = children[UI_COMP_MENU_ITEM_CONTAINER_MENU_ITEM_CONTAINER];
    lv_obj_t * img = children[UI_COMP_MENU_ITEM_CONTAINER_IMG];
    lv_obj_t * label = children[UI_COMP_MENU_ITEM_CONTAINER_LABEL];

    lv_obj_set_style_bg_color(menu_item_container, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(menu_item_container, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_img_recolor(img, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_img_recolor_opa(img, LV_OPA_100, LV_PART_MAIN);

    lv_obj_set_style_text_color(label, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_text_opa(label, LV_OPA_100, LV_PART_MAIN);
}

void ui_floder_screen_loaded(lv_event_t * e)
{
	// Your code here
    (void)e;
}

void ui_setting_screen_loaded(lv_event_t * e)
{
	// Your code here
    (void)e;
}

void ui_badge_screen_loaded(lv_event_t * e)
{
	// Your code here
    (void)e;
}

void ui_file_screen_loaded(lv_event_t * e)
{
	// Your code here
    (void)e;
}

