// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

lv_obj_t * ui_badge_screen = NULL;
lv_obj_t * ui_badge_screen_left_container = NULL;
lv_obj_t * ui_badge_screen_company_name = NULL;
lv_obj_t * ui_badge_screen_NFC_ICON = NULL;
lv_obj_t * ui_badge_screen_main_container = NULL;
lv_obj_t * ui_badge_screen_top_container = NULL;
lv_obj_t * ui_badge_screen_Container6 = NULL;
lv_obj_t * ui_badge_screen_name = NULL;
lv_obj_t * ui_badge_screen_job = NULL;
lv_obj_t * ui_badge_screen_Profile_picture = NULL;
lv_obj_t * ui_badge_screen_image = NULL;
lv_obj_t * ui_badge_screen_middle_container = NULL;
lv_obj_t * ui_badge_screen_email_container = NULL;
lv_obj_t * ui_badge_screen_tag = NULL;
lv_obj_t * ui_badge_screen_content = NULL;
lv_obj_t * ui_badge_screen_phone_container = NULL;
lv_obj_t * ui_badge_screen_tag2 = NULL;
lv_obj_t * ui_badge_screen_content2 = NULL;
lv_obj_t * ui_badge_screen_site_container = NULL;
lv_obj_t * ui_badge_screen_tag3 = NULL;
lv_obj_t * ui_badge_screen_content3 = NULL;
lv_obj_t * ui_badge_screen_bottom_container = NULL;
lv_obj_t * ui_badge_screen_Label6 = NULL;
lv_obj_t * ui_badge_screen_image_QR = NULL;
/**************** extern keyboard group functions start ************************/
static void ui_badge_screen_keyboard_group_init(void);
static void ui_badge_screen_keyboard_group_destroy(void);

static void ui_badge_screen_keyboard_handler(lv_event_t * e);
/**************** extern keyboard group functions end ************************/
// event funtions
void ui_event_badge_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_badge_screen_loaded(e);

        // add keyboard group
        ui_badge_screen_keyboard_group_init();
    } else if(event_code == LV_EVENT_KEY) {
        ui_badge_screen_keyboard_handler(e);
    }
}

// build funtions

void ui_badge_screen_screen_init(void)
{
    ui_badge_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_badge_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_badge_screen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_badge_screen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    ui_badge_screen_left_container = lv_obj_create(ui_badge_screen);
    lv_obj_remove_style_all(ui_badge_screen_left_container);
    lv_obj_set_width(ui_badge_screen_left_container, lv_pct(16));
    lv_obj_set_height(ui_badge_screen_left_container, lv_pct(100));
    lv_obj_set_align(ui_badge_screen_left_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badge_screen_left_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_badge_screen_left_container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badge_screen_left_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_company_name = lv_label_create(ui_badge_screen_left_container);
    lv_obj_set_width(ui_badge_screen_company_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_company_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_badge_screen_company_name, 75);
    lv_obj_set_y(ui_badge_screen_company_name, -120);
    lv_obj_set_align(ui_badge_screen_company_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_company_name, "TUYA INC");
    lv_obj_set_style_text_color(ui_badge_screen_company_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_badge_screen_company_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_badge_screen_company_name, &ui_font_terminus_bold_32_2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_badge_screen_company_name, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_NFC_ICON = lv_image_create(ui_badge_screen_left_container);
    lv_image_set_src(ui_badge_screen_NFC_ICON, &ui_img_image_badge_nfc_32_png);
    lv_obj_set_width(ui_badge_screen_NFC_ICON, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_NFC_ICON, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_badge_screen_NFC_ICON, 0);
    lv_obj_set_y(ui_badge_screen_NFC_ICON, 120);
    lv_obj_set_align(ui_badge_screen_NFC_ICON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_badge_screen_NFC_ICON, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_badge_screen_NFC_ICON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_badge_screen_main_container = lv_obj_create(ui_badge_screen);
    lv_obj_remove_style_all(ui_badge_screen_main_container);
    lv_obj_set_width(ui_badge_screen_main_container, lv_pct(84));
    lv_obj_set_height(ui_badge_screen_main_container, lv_pct(100));
    lv_obj_set_align(ui_badge_screen_main_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_badge_screen_main_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_badge_screen_main_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_badge_screen_main_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_badge_screen_main_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badge_screen_main_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_top_container = lv_obj_create(ui_badge_screen_main_container);
    lv_obj_remove_style_all(ui_badge_screen_top_container);
    lv_obj_set_width(ui_badge_screen_top_container, lv_pct(100));
    lv_obj_set_height(ui_badge_screen_top_container, lv_pct(35));
    lv_obj_set_align(ui_badge_screen_top_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_badge_screen_top_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_badge_screen_top_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_badge_screen_top_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_badge_screen_Container6 = lv_obj_create(ui_badge_screen_top_container);
    lv_obj_remove_style_all(ui_badge_screen_Container6);
    lv_obj_set_width(ui_badge_screen_Container6, lv_pct(65));
    lv_obj_set_height(ui_badge_screen_Container6, lv_pct(100));
    lv_obj_set_align(ui_badge_screen_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_badge_screen_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_badge_screen_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_badge_screen_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_badge_screen_Container6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_badge_screen_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_badge_screen_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_badge_screen_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_name = lv_label_create(ui_badge_screen_Container6);
    lv_obj_set_width(ui_badge_screen_name, lv_pct(100));
    lv_obj_set_height(ui_badge_screen_name, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_badge_screen_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_name, "TUYA HelloWorld");
    lv_obj_set_style_text_align(ui_badge_screen_name, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_badge_screen_name, &ui_font_JetBrains_Mono_Bold_32_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_job = lv_label_create(ui_badge_screen_Container6);
    lv_obj_set_width(ui_badge_screen_job, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_job, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_job, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_job, "SENIOR PRODUCT DIRECTOR");
    lv_obj_set_style_text_color(ui_badge_screen_job, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_badge_screen_job, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_badge_screen_job, &ui_font_terminus_bold_16_1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_badge_screen_job, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badge_screen_job, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_badge_screen_job, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_badge_screen_job, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_badge_screen_job, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_badge_screen_job, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_Profile_picture = lv_obj_create(ui_badge_screen_top_container);
    lv_obj_remove_style_all(ui_badge_screen_Profile_picture);
    lv_obj_set_height(ui_badge_screen_Profile_picture, 100);
    lv_obj_set_width(ui_badge_screen_Profile_picture, lv_pct(35));
    lv_obj_set_align(ui_badge_screen_Profile_picture, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badge_screen_Profile_picture, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_badge_screen_image = lv_image_create(ui_badge_screen_Profile_picture);
    lv_image_set_src(ui_badge_screen_image, &ui_img_image_badge_tuyaopen_logo_png);
    lv_obj_set_width(ui_badge_screen_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_badge_screen_image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_badge_screen_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_badge_screen_middle_container = lv_obj_create(ui_badge_screen_main_container);
    lv_obj_remove_style_all(ui_badge_screen_middle_container);
    lv_obj_set_width(ui_badge_screen_middle_container, lv_pct(100));
    lv_obj_set_height(ui_badge_screen_middle_container, lv_pct(40));
    lv_obj_set_align(ui_badge_screen_middle_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_badge_screen_middle_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_badge_screen_middle_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_badge_screen_middle_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_badge_screen_middle_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badge_screen_middle_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_badge_screen_middle_container, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_badge_screen_middle_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_badge_screen_middle_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_badge_screen_middle_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_email_container = lv_obj_create(ui_badge_screen_middle_container);
    lv_obj_remove_style_all(ui_badge_screen_email_container);
    lv_obj_set_width(ui_badge_screen_email_container, lv_pct(85));
    lv_obj_set_height(ui_badge_screen_email_container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_email_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badge_screen_email_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_badge_screen_email_container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_badge_screen_email_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_badge_screen_email_container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_badge_screen_email_container, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_tag = lv_label_create(ui_badge_screen_email_container);
    lv_obj_set_width(ui_badge_screen_tag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_tag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_tag, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_badge_screen_tag, "EMAIL: ");
    lv_obj_set_style_text_font(ui_badge_screen_tag, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_content = lv_label_create(ui_badge_screen_email_container);
    lv_obj_set_width(ui_badge_screen_content, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_content, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_content, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_content, "xxx@tuya.com");
    lv_obj_set_style_text_font(ui_badge_screen_content, &ui_font_terminus_bold_18_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_phone_container = lv_obj_create(ui_badge_screen_middle_container);
    lv_obj_remove_style_all(ui_badge_screen_phone_container);
    lv_obj_set_width(ui_badge_screen_phone_container, lv_pct(85));
    lv_obj_set_height(ui_badge_screen_phone_container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_phone_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badge_screen_phone_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_badge_screen_phone_container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_badge_screen_phone_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_badge_screen_phone_container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_badge_screen_phone_container, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_tag2 = lv_label_create(ui_badge_screen_phone_container);
    lv_obj_set_width(ui_badge_screen_tag2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_tag2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_tag2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_badge_screen_tag2, "PHONE: ");
    lv_obj_set_style_text_font(ui_badge_screen_tag2, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_content2 = lv_label_create(ui_badge_screen_phone_container);
    lv_obj_set_width(ui_badge_screen_content2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_content2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_content2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_content2, "844-672-5646");
    lv_obj_set_style_text_font(ui_badge_screen_content2, &ui_font_terminus_bold_18_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_site_container = lv_obj_create(ui_badge_screen_middle_container);
    lv_obj_remove_style_all(ui_badge_screen_site_container);
    lv_obj_set_width(ui_badge_screen_site_container, lv_pct(85));
    lv_obj_set_height(ui_badge_screen_site_container, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_site_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badge_screen_site_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_badge_screen_site_container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_badge_screen_site_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_badge_screen_site_container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_badge_screen_site_container, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_tag3 = lv_label_create(ui_badge_screen_site_container);
    lv_obj_set_width(ui_badge_screen_tag3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_tag3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_tag3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_badge_screen_tag3, "SITE:");
    lv_obj_set_style_text_font(ui_badge_screen_tag3, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_content3 = lv_label_create(ui_badge_screen_site_container);
    lv_obj_set_width(ui_badge_screen_content3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_content3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_content3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_content3, "www.tuyaopen.ai");
    lv_obj_set_style_text_font(ui_badge_screen_content3, &ui_font_terminus_bold_18_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_bottom_container = lv_obj_create(ui_badge_screen_main_container);
    lv_obj_remove_style_all(ui_badge_screen_bottom_container);
    lv_obj_set_width(ui_badge_screen_bottom_container, lv_pct(100));
    lv_obj_set_height(ui_badge_screen_bottom_container, lv_pct(25));
    lv_obj_set_align(ui_badge_screen_bottom_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_badge_screen_bottom_container, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_badge_screen_bottom_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_badge_screen_bottom_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_badge_screen_bottom_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_badge_screen_bottom_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_Label6 = lv_label_create(ui_badge_screen_bottom_container);
    lv_obj_set_width(ui_badge_screen_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_badge_screen_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_badge_screen_Label6, "Build AI-Agent Hardware \nWith TuyaOpen");
    lv_obj_set_style_text_align(ui_badge_screen_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_badge_screen_Label6, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_badge_screen_image_QR = lv_image_create(ui_badge_screen_bottom_container);
    lv_image_set_src(ui_badge_screen_image_QR, &ui_img_image_badge_tuyaopen_qr_48_png);
    lv_obj_set_width(ui_badge_screen_image_QR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_badge_screen_image_QR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_badge_screen_image_QR, 121);
    lv_obj_set_y(ui_badge_screen_image_QR, -4);
    lv_obj_set_align(ui_badge_screen_image_QR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_badge_screen_image_QR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_badge_screen_image_QR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_badge_screen, ui_event_badge_screen, LV_EVENT_ALL, NULL);

}

void ui_badge_screen_screen_destroy(void)
{
    if(ui_badge_screen) lv_obj_del(ui_badge_screen);

    // NULL screen variables
    ui_badge_screen = NULL;
    ui_badge_screen_left_container = NULL;
    ui_badge_screen_company_name = NULL;
    ui_badge_screen_NFC_ICON = NULL;
    ui_badge_screen_main_container = NULL;
    ui_badge_screen_top_container = NULL;
    ui_badge_screen_Container6 = NULL;
    ui_badge_screen_name = NULL;
    ui_badge_screen_job = NULL;
    ui_badge_screen_Profile_picture = NULL;
    ui_badge_screen_image = NULL;
    ui_badge_screen_middle_container = NULL;
    ui_badge_screen_email_container = NULL;
    ui_badge_screen_tag = NULL;
    ui_badge_screen_content = NULL;
    ui_badge_screen_phone_container = NULL;
    ui_badge_screen_tag2 = NULL;
    ui_badge_screen_content2 = NULL;
    ui_badge_screen_site_container = NULL;
    ui_badge_screen_tag3 = NULL;
    ui_badge_screen_content3 = NULL;
    ui_badge_screen_bottom_container = NULL;
    ui_badge_screen_Label6 = NULL;
    ui_badge_screen_image_QR = NULL;

    ui_badge_screen_keyboard_group_destroy();
}

/****************************** keyboard start ******************************/
// static uint32_t __focus_obj_count = 0;

static lv_group_t * sg_keyboard_group = NULL;

static void ui_badge_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        // TODO: add focus objects
        // add group to indev
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_badge_screen_keyboard_group_init: failed to create group");
        return;
    }

    // add ui_badge_screen to group
    lv_group_add_obj(sg_keyboard_group, ui_badge_screen);

    // TODO: add focus objects

    // add group to indev
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

static void ui_badge_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

static void ui_badge_screen_keyboard_handler(lv_event_t * e)
{
    lv_key_t key = lv_event_get_key(e);

    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
        case LV_KEY_PREV:
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
        case LV_KEY_NEXT:
            break;
        case LV_KEY_ENTER:
            break;
        case LV_KEY_ESC:
            _ui_screen_change(&ui_home_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_home_screen_screen_init);
            break;
        default:
            break;
    }
}

/****************************** keyboard end ******************************/
