// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef UI_BADGE_SCREEN_H
#define UI_BADGE_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_badge_screen
extern void ui_badge_screen_screen_init(void);
extern void ui_badge_screen_screen_destroy(void);
extern void ui_event_badge_screen(lv_event_t * e);
extern lv_obj_t * ui_badge_screen;
extern lv_obj_t * ui_badge_screen_left_container;
extern lv_obj_t * ui_badge_screen_company_name;
extern lv_obj_t * ui_badge_screen_NFC_ICON;
extern lv_obj_t * ui_badge_screen_main_container;
extern lv_obj_t * ui_badge_screen_top_container;
extern lv_obj_t * ui_badge_screen_Container6;
extern lv_obj_t * ui_badge_screen_name;
extern lv_obj_t * ui_badge_screen_job;
extern lv_obj_t * ui_badge_screen_Profile_picture;
extern lv_obj_t * ui_badge_screen_image;
extern lv_obj_t * ui_badge_screen_middle_container;
extern lv_obj_t * ui_badge_screen_email_container;
extern lv_obj_t * ui_badge_screen_tag;
extern lv_obj_t * ui_badge_screen_content;
extern lv_obj_t * ui_badge_screen_phone_container;
extern lv_obj_t * ui_badge_screen_tag2;
extern lv_obj_t * ui_badge_screen_content2;
extern lv_obj_t * ui_badge_screen_site_container;
extern lv_obj_t * ui_badge_screen_tag3;
extern lv_obj_t * ui_badge_screen_content3;
extern lv_obj_t * ui_badge_screen_bottom_container;
extern lv_obj_t * ui_badge_screen_Label6;
extern lv_obj_t * ui_badge_screen_image_QR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

