// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

lv_obj_t * ui_floder_screen = NULL;
lv_obj_t * ui_floder_screen_status_bar = NULL;
lv_obj_t * ui_floder_screen_battery = NULL;
lv_obj_t * ui_floder_screen_tf_card = NULL;
lv_obj_t * ui_floder_screen_remain_size = NULL;
lv_obj_t * ui_floder_screen_title = NULL;
lv_obj_t * ui_floder_screen_list_container = NULL;
lv_obj_t * ui_floder_screen_floder_item = NULL;
lv_obj_t * ui_floder_screen_floder_item_container1 = NULL;
lv_obj_t * ui_floder_screen_floder_item_container2 = NULL;
lv_obj_t * ui_floder_screen_floder_item_container3 = NULL;
/**************** extern keyboard group functions start ************************/
static void ui_floder_screen_keyboard_group_init(void);
static void ui_floder_screen_keyboard_group_destroy(void);

static void ui_floder_screen_keyboard_handler(lv_event_t * e);
/**************** extern keyboard group functions end ************************/
// event funtions
void ui_event_floder_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_floder_screen_loaded(e);

        // add keyboard group
        ui_floder_screen_keyboard_group_init();
    } else if(event_code == LV_EVENT_KEY) {
        ui_floder_screen_keyboard_handler(e);
    }
}

// build funtions

void ui_floder_screen_screen_init(void)
{
    ui_floder_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_floder_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_status_bar = lv_obj_create(ui_floder_screen);
    lv_obj_remove_style_all(ui_floder_screen_status_bar);
    lv_obj_set_height(ui_floder_screen_status_bar, 30);
    lv_obj_set_width(ui_floder_screen_status_bar, lv_pct(100));
    lv_obj_set_x(ui_floder_screen_status_bar, -1);
    lv_obj_set_y(ui_floder_screen_status_bar, 0);
    lv_obj_set_align(ui_floder_screen_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_floder_screen_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_floder_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_floder_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_foreground);
    lv_obj_set_style_border_width(ui_floder_screen_status_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_floder_screen_status_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floder_screen_battery = lv_image_create(ui_floder_screen_status_bar);
    lv_image_set_src(ui_floder_screen_battery, &ui_img_image_statue_bar_battery_battery_full_30_png);
    lv_obj_set_width(ui_floder_screen_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floder_screen_battery, -10);
    lv_obj_set_y(ui_floder_screen_battery, 0);
    lv_obj_set_align(ui_floder_screen_battery, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_floder_screen_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_floder_screen_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_tf_card = lv_image_create(ui_floder_screen_status_bar);
    lv_image_set_src(ui_floder_screen_tf_card, &ui_img_image_statue_bar_sd_tf_30_png);
    lv_obj_set_width(ui_floder_screen_tf_card, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_tf_card, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floder_screen_tf_card, 5);
    lv_obj_set_y(ui_floder_screen_tf_card, 0);
    lv_obj_set_align(ui_floder_screen_tf_card, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_floder_screen_tf_card, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_floder_screen_tf_card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_remain_size = lv_label_create(ui_floder_screen_status_bar);
    lv_obj_set_width(ui_floder_screen_remain_size, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_remain_size, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floder_screen_remain_size, 45);
    lv_obj_set_y(ui_floder_screen_remain_size, 0);
    lv_obj_set_align(ui_floder_screen_remain_size, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_floder_screen_remain_size, "31.25 GB(TF)");
    lv_obj_set_style_text_font(ui_floder_screen_remain_size, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floder_screen_title = lv_label_create(ui_floder_screen_status_bar);
    lv_obj_set_width(ui_floder_screen_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floder_screen_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_floder_screen_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_floder_screen_title, "Floder");
    lv_obj_set_style_text_font(ui_floder_screen_title, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floder_screen_list_container = lv_obj_create(ui_floder_screen);
    lv_obj_remove_style_all(ui_floder_screen_list_container);
    lv_obj_set_height(ui_floder_screen_list_container, 270);
    lv_obj_set_width(ui_floder_screen_list_container, lv_pct(100));
    lv_obj_set_align(ui_floder_screen_list_container, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_floder_screen_list_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_floder_screen_list_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_floder_screen_list_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_floder_screen_floder_item = ui_floder_item_container_create(ui_floder_screen_list_container);
    lv_obj_set_x(ui_floder_screen_floder_item, 0);
    lv_obj_set_y(ui_floder_screen_floder_item, 0);

    lv_image_set_src(ui_comp_get_child(ui_floder_screen_floder_item, UI_COMP_FLODER_ITEM_CONTAINER_ICON),
                     &ui_img_image_floder_floder_32_png);

    lv_label_set_text(ui_comp_get_child(ui_floder_screen_floder_item, UI_COMP_FLODER_ITEM_CONTAINER_LABEL), "Image");

    ui_floder_screen_floder_item_container1 = ui_floder_item_container_create(ui_floder_screen_list_container);
    lv_obj_set_x(ui_floder_screen_floder_item_container1, 0);
    lv_obj_set_y(ui_floder_screen_floder_item_container1, 0);

    lv_image_set_src(ui_comp_get_child(ui_floder_screen_floder_item_container1, UI_COMP_FLODER_ITEM_CONTAINER_ICON),
                     &ui_img_image_floder_txt_32_png);

    lv_label_set_text(ui_comp_get_child(ui_floder_screen_floder_item_container1, UI_COMP_FLODER_ITEM_CONTAINER_LABEL),
                      "1.txt");

    ui_floder_screen_floder_item_container2 = ui_floder_item_container_create(ui_floder_screen_list_container);
    lv_obj_set_x(ui_floder_screen_floder_item_container2, 0);
    lv_obj_set_y(ui_floder_screen_floder_item_container2, 0);

    lv_image_set_src(ui_comp_get_child(ui_floder_screen_floder_item_container2, UI_COMP_FLODER_ITEM_CONTAINER_ICON),
                     &ui_img_image_floder_png_32_png);

    lv_label_set_text(ui_comp_get_child(ui_floder_screen_floder_item_container2, UI_COMP_FLODER_ITEM_CONTAINER_LABEL),
                      "1.png");

    ui_floder_screen_floder_item_container3 = ui_floder_item_container_create(ui_floder_screen_list_container);
    lv_obj_set_x(ui_floder_screen_floder_item_container3, 0);
    lv_obj_set_y(ui_floder_screen_floder_item_container3, 0);

    lv_image_set_src(ui_comp_get_child(ui_floder_screen_floder_item_container3, UI_COMP_FLODER_ITEM_CONTAINER_ICON),
                     &ui_img_image_floder_epub_32_png);

    lv_label_set_text(ui_comp_get_child(ui_floder_screen_floder_item_container3, UI_COMP_FLODER_ITEM_CONTAINER_LABEL),
                      "1.epub");

    lv_obj_add_event_cb(ui_floder_screen, ui_event_floder_screen, LV_EVENT_ALL, NULL);

}

void ui_floder_screen_screen_destroy(void)
{
    if(ui_floder_screen) lv_obj_del(ui_floder_screen);

    // NULL screen variables
    ui_floder_screen = NULL;
    ui_floder_screen_status_bar = NULL;
    ui_floder_screen_battery = NULL;
    ui_floder_screen_tf_card = NULL;
    ui_floder_screen_remain_size = NULL;
    ui_floder_screen_title = NULL;
    ui_floder_screen_list_container = NULL;
    ui_floder_screen_floder_item = NULL;
    ui_floder_screen_floder_item_container1 = NULL;
    ui_floder_screen_floder_item_container2 = NULL;
    ui_floder_screen_floder_item_container3 = NULL;

    ui_floder_screen_keyboard_group_destroy();
}

/****************************** keyboard start ******************************/
// static uint32_t __focus_obj_count = 0;

static lv_group_t * sg_keyboard_group = NULL;

static void ui_floder_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        // TODO: add focus objects
        // add group to indev
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_floder_screen_keyboard_group_init: failed to create group");
        return;
    }

    // add ui_floder_screen to group
    lv_group_add_obj(sg_keyboard_group, ui_floder_screen);

    // TODO: add focus objects

    // add group to indev
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

static void ui_floder_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

static void ui_floder_screen_keyboard_handler(lv_event_t * e)
{
    lv_key_t key = lv_event_get_key(e);

    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
        case LV_KEY_PREV:
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
        case LV_KEY_NEXT:
            break;
        case LV_KEY_ENTER:
            break;
        case LV_KEY_ESC:
            _ui_screen_change(&ui_home_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_home_screen_screen_init);
            break;
        default:
            break;
    }
}

/****************************** keyboard end ******************************/
