// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef UI_FILE_SCREEN_H
#define UI_FILE_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_file_screen
extern void ui_file_screen_screen_init(void);
extern void ui_file_screen_screen_destroy(void);
extern void ui_event_file_screen(lv_event_t * e);
extern lv_obj_t * ui_file_screen;
extern lv_obj_t * ui_file_screen_file_container;
extern lv_obj_t * ui_file_screen_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

