// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

lv_obj_t * ui_file_screen = NULL;
lv_obj_t * ui_file_screen_file_container = NULL;
lv_obj_t * ui_file_screen_Image4 = NULL;
// event funtions
void ui_event_file_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_file_screen_loaded(e);
    }
}

// build funtions

void ui_file_screen_screen_init(void)
{
    ui_file_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_file_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_file_screen_file_container = lv_obj_create(ui_file_screen);
    lv_obj_remove_style_all(ui_file_screen_file_container);
    lv_obj_set_width(ui_file_screen_file_container, lv_pct(100));
    lv_obj_set_height(ui_file_screen_file_container, lv_pct(100));
    lv_obj_set_align(ui_file_screen_file_container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_file_screen_file_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_file_screen_Image4 = lv_image_create(ui_file_screen);
    lv_image_set_src(ui_file_screen_Image4, &ui_img_image_floder_wallpaper_png);
    lv_obj_set_width(ui_file_screen_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_file_screen_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_file_screen_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_file_screen_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_file_screen_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_file_screen, ui_event_file_screen, LV_EVENT_ALL, NULL);

}

void ui_file_screen_screen_destroy(void)
{
    if(ui_file_screen) lv_obj_del(ui_file_screen);

    // NULL screen variables
    ui_file_screen = NULL;
    ui_file_screen_file_container = NULL;
    ui_file_screen_Image4 = NULL;

}
