// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef UI_FLODER_SCREEN_H
#define UI_FLODER_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_floder_screen
extern void ui_floder_screen_screen_init(void);
extern void ui_floder_screen_screen_destroy(void);
extern void ui_event_floder_screen(lv_event_t * e);
extern lv_obj_t * ui_floder_screen;
extern lv_obj_t * ui_floder_screen_status_bar;
extern lv_obj_t * ui_floder_screen_battery;
extern lv_obj_t * ui_floder_screen_tf_card;
extern lv_obj_t * ui_floder_screen_remain_size;
extern lv_obj_t * ui_floder_screen_title;
extern lv_obj_t * ui_floder_screen_list_container;
extern lv_obj_t * ui_floder_screen_floder_item;
extern lv_obj_t * ui_floder_screen_floder_item_container1;
extern lv_obj_t * ui_floder_screen_floder_item_container2;
extern lv_obj_t * ui_floder_screen_floder_item_container3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

