// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#ifndef UI_SETTING_SCREEN_H
#define UI_SETTING_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting_screen
extern void ui_setting_screen_screen_init(void);
extern void ui_setting_screen_screen_destroy(void);
extern void ui_event_setting_screen(lv_event_t * e);
extern lv_obj_t * ui_setting_screen;
extern lv_obj_t * ui_setting_screen_status_bar;
extern lv_obj_t * ui_setting_screen_battery;
extern lv_obj_t * ui_setting_screen_title;
extern lv_obj_t * ui_setting_screen_list_container;
extern lv_obj_t * ui_setting_screen_backlight;
extern lv_obj_t * ui_setting_screen_backlight2;
extern lv_obj_t * ui_setting_screen_backlight3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

