// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

lv_obj_t * ui_setting_screen = NULL;
lv_obj_t * ui_setting_screen_status_bar = NULL;
lv_obj_t * ui_setting_screen_battery = NULL;
lv_obj_t * ui_setting_screen_title = NULL;
lv_obj_t * ui_setting_screen_list_container = NULL;
lv_obj_t * ui_setting_screen_backlight = NULL;
lv_obj_t * ui_setting_screen_backlight2 = NULL;
lv_obj_t * ui_setting_screen_backlight3 = NULL;
/**************** extern keyboard group functions start ************************/
static void ui_setting_screen_keyboard_group_init(void);
static void ui_setting_screen_keyboard_group_destroy(void);

static void ui_setting_screen_keyboard_handler(lv_event_t * e);
/**************** extern keyboard group functions end ************************/
// event funtions
void ui_event_setting_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ui_setting_screen_loaded(e);

        // add keyboard group
        ui_setting_screen_keyboard_group_init();
    } else if(event_code == LV_EVENT_KEY) {
        ui_setting_screen_keyboard_handler(e);
    }
}

// build funtions

void ui_setting_screen_screen_init(void)
{
    ui_setting_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_screen_status_bar = lv_obj_create(ui_setting_screen);
    lv_obj_remove_style_all(ui_setting_screen_status_bar);
    lv_obj_set_height(ui_setting_screen_status_bar, 30);
    lv_obj_set_width(ui_setting_screen_status_bar, lv_pct(100));
    lv_obj_set_x(ui_setting_screen_status_bar, -1);
    lv_obj_set_y(ui_setting_screen_status_bar, 0);
    lv_obj_set_align(ui_setting_screen_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_setting_screen_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_setting_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_setting_screen_status_bar, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_foreground);
    lv_obj_set_style_border_width(ui_setting_screen_status_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_setting_screen_status_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting_screen_battery = lv_image_create(ui_setting_screen_status_bar);
    lv_image_set_src(ui_setting_screen_battery, &ui_img_image_statue_bar_battery_battery_full_30_png);
    lv_obj_set_width(ui_setting_screen_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setting_screen_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setting_screen_battery, -10);
    lv_obj_set_y(ui_setting_screen_battery, 0);
    lv_obj_set_align(ui_setting_screen_battery, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_setting_screen_battery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_setting_screen_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_screen_title = lv_label_create(ui_setting_screen_status_bar);
    lv_obj_set_width(ui_setting_screen_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setting_screen_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_setting_screen_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setting_screen_title, "Setting");
    lv_obj_set_style_text_font(ui_setting_screen_title, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting_screen_list_container = lv_obj_create(ui_setting_screen);
    lv_obj_remove_style_all(ui_setting_screen_list_container);
    lv_obj_set_height(ui_setting_screen_list_container, 270);
    lv_obj_set_width(ui_setting_screen_list_container, lv_pct(100));
    lv_obj_set_align(ui_setting_screen_list_container, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_setting_screen_list_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_screen_list_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_setting_screen_list_container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_screen_backlight = ui_list_item_create(ui_setting_screen_list_container);
    lv_obj_set_x(ui_setting_screen_backlight, 0);
    lv_obj_set_y(ui_setting_screen_backlight, 0);

    lv_image_set_src(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_LEFT_ICON),
                     &ui_img_image_setting_light_32_png);

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_LEFT_LABEL), "Backlight");

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_RIGHT_OPTIONS), "ON");
    lv_obj_remove_flag(ui_comp_get_child(ui_setting_screen_backlight, UI_COMP_LIST_ITEM_RIGHT_OPTIONS),
                       LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_setting_screen_backlight2 = ui_list_item_create(ui_setting_screen_list_container);
    lv_obj_set_x(ui_setting_screen_backlight2, 0);
    lv_obj_set_y(ui_setting_screen_backlight2, 0);

    lv_image_set_src(ui_comp_get_child(ui_setting_screen_backlight2, UI_COMP_LIST_ITEM_LEFT_ICON),
                     &ui_img_image_setting_sleep_time_32_png);

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight2, UI_COMP_LIST_ITEM_LEFT_LABEL), "Sleep Time");

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight2, UI_COMP_LIST_ITEM_RIGHT_OPTIONS), "5 Min");
    lv_obj_remove_flag(ui_comp_get_child(ui_setting_screen_backlight2, UI_COMP_LIST_ITEM_RIGHT_OPTIONS),
                       LV_OBJ_FLAG_HIDDEN);    /// Flags

    ui_setting_screen_backlight3 = ui_list_item_create(ui_setting_screen_list_container);
    lv_obj_set_x(ui_setting_screen_backlight3, 0);
    lv_obj_set_y(ui_setting_screen_backlight3, 0);

    lv_image_set_src(ui_comp_get_child(ui_setting_screen_backlight3, UI_COMP_LIST_ITEM_LEFT_ICON),
                     &ui_img_image_setting_language_32_png);

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight3, UI_COMP_LIST_ITEM_LEFT_LABEL), "Language");

    lv_label_set_text(ui_comp_get_child(ui_setting_screen_backlight3, UI_COMP_LIST_ITEM_RIGHT_OPTIONS), "English");
    lv_obj_remove_flag(ui_comp_get_child(ui_setting_screen_backlight3, UI_COMP_LIST_ITEM_RIGHT_OPTIONS),
                       LV_OBJ_FLAG_HIDDEN);    /// Flags

    lv_obj_add_event_cb(ui_setting_screen, ui_event_setting_screen, LV_EVENT_ALL, NULL);

}

void ui_setting_screen_screen_destroy(void)
{
    if(ui_setting_screen) lv_obj_del(ui_setting_screen);

    // NULL screen variables
    ui_setting_screen = NULL;
    ui_setting_screen_status_bar = NULL;
    ui_setting_screen_battery = NULL;
    ui_setting_screen_title = NULL;
    ui_setting_screen_list_container = NULL;
    ui_setting_screen_backlight = NULL;
    ui_setting_screen_backlight2 = NULL;
    ui_setting_screen_backlight3 = NULL;

    ui_setting_screen_keyboard_group_destroy();
}

/****************************** keyboard start ******************************/
// static uint32_t __focus_obj_count = 0;

static lv_group_t * sg_keyboard_group = NULL;

static void ui_setting_screen_keyboard_group_init(void)
{
    if (sg_keyboard_group) {
        // TODO: add focus objects
        // add group to indev
        lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
        return;
    }

    sg_keyboard_group = lv_group_create();
    if (NULL == sg_keyboard_group) {
        LV_LOG_ERROR("ui_setting_screen_keyboard_group_init: failed to create group");
        return;
    }

    // add ui_setting_screen to group
    lv_group_add_obj(sg_keyboard_group, ui_setting_screen);

    // TODO: add focus objects

    // add group to indev
    lv_indev_set_group(lv_indev_get_next(NULL), sg_keyboard_group);
}

static void ui_setting_screen_keyboard_group_destroy(void)
{
    if (!sg_keyboard_group) {
        return;
    }

    lv_group_delete(sg_keyboard_group);
    sg_keyboard_group = NULL;
}

static void ui_setting_screen_keyboard_handler(lv_event_t * e)
{
    lv_key_t key = lv_event_get_key(e);

    switch (key) {
        case LV_KEY_UP:
        case LV_KEY_LEFT:
        case LV_KEY_PREV:
            break;
        case LV_KEY_DOWN:
        case LV_KEY_RIGHT:
        case LV_KEY_NEXT:
            break;
        case LV_KEY_ENTER:
            break;
        case LV_KEY_ESC:
            _ui_screen_change(&ui_home_screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_home_screen_screen_init);
            break;
        default:
            break;
    }
}

/****************************** keyboard end ******************************/
