// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

void ui_event_comp_menu_item_container_menu_item_container(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t ** comp_menu_item_container = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_FOCUSED) {
        ui_home_menu_item_focused_callback(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        ui_home_menu_item_defocused_callback(e);
    }
}

// COMPONENT menu item container

lv_obj_t * ui_menu_item_container_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_menu_item_container;
    cui_menu_item_container = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_menu_item_container);
    lv_obj_set_width(cui_menu_item_container, 110);
    lv_obj_set_height(cui_menu_item_container, 110);
    lv_obj_set_align(cui_menu_item_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_menu_item_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_menu_item_container, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_menu_item_container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_menu_item_container, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_menu_item_container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(cui_menu_item_container, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_outline_color(cui_menu_item_container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(cui_menu_item_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(cui_menu_item_container, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_menu_item_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_img;
    cui_img = lv_image_create(cui_menu_item_container);
    lv_obj_set_width(cui_img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_img, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_img, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(cui_img, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_label;
    cui_label = lv_label_create(cui_menu_item_container);
    lv_obj_set_width(cui_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label, "Menu");
    lv_obj_add_flag(cui_label, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(cui_label, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_font(cui_label, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_MENU_ITEM_CONTAINER_NUM);
    children[UI_COMP_MENU_ITEM_CONTAINER_MENU_ITEM_CONTAINER] = cui_menu_item_container;
    children[UI_COMP_MENU_ITEM_CONTAINER_IMG] = cui_img;
    children[UI_COMP_MENU_ITEM_CONTAINER_LABEL] = cui_label;
    lv_obj_add_event_cb(cui_menu_item_container, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_menu_item_container, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_menu_item_container, ui_event_comp_menu_item_container_menu_item_container, LV_EVENT_ALL,
                        children);
    ui_comp_menu_item_container_create_hook(cui_menu_item_container);
    return cui_menu_item_container;
}

