// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: e-Paper

#include "../ui.h"

// COMPONENT list item

lv_obj_t * ui_list_item_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_list_item;
    cui_list_item = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_list_item);
    lv_obj_set_width(cui_list_item, lv_pct(100));
    lv_obj_set_height(cui_list_item, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_list_item, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_list_item, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_list_item, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_list_item, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_list_item, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(cui_list_item, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_border_width(cui_list_item, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_list_item, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_list_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_list_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_list_item, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_list_item, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_left;
    cui_left = lv_obj_create(cui_list_item);
    lv_obj_remove_style_all(cui_left);
    lv_obj_set_width(cui_left, lv_pct(50));
    lv_obj_set_height(cui_left, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_left, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_left, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_left, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_left, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_left, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_icon;
    cui_icon = lv_image_create(cui_left);
    lv_obj_set_width(cui_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(cui_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_label;
    cui_label = lv_label_create(cui_left);
    lv_obj_set_width(cui_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label, LV_ALIGN_CENTER);
    lv_label_set_text(cui_label, "image");
    lv_obj_add_flag(cui_label, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_font(cui_label, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_right;
    cui_right = lv_obj_create(cui_list_item);
    lv_obj_remove_style_all(cui_right);
    lv_obj_set_width(cui_right, lv_pct(30));
    lv_obj_set_height(cui_right, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_right, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_right, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_options;
    cui_options = lv_label_create(cui_right);
    lv_obj_set_width(cui_options, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_options, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_options, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_options, "option1");
    lv_obj_add_flag(cui_options, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_set_style_text_font(cui_options, &ui_font_terminus_bold_16_2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_options, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_options, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_options, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_options, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_LIST_ITEM_NUM);
    children[UI_COMP_LIST_ITEM_LIST_ITEM] = cui_list_item;
    children[UI_COMP_LIST_ITEM_LEFT] = cui_left;
    children[UI_COMP_LIST_ITEM_LEFT_ICON] = cui_icon;
    children[UI_COMP_LIST_ITEM_LEFT_LABEL] = cui_label;
    children[UI_COMP_LIST_ITEM_RIGHT] = cui_right;
    children[UI_COMP_LIST_ITEM_RIGHT_OPTIONS] = cui_options;
    lv_obj_add_event_cb(cui_list_item, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_list_item, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_list_item_create_hook(cui_list_item);
    return cui_list_item;
}

